### ISSUE TITLE
Detailed results of ScienceQA-IMG

### ISSUE THREAD

**Issue by thecharm** [open-compass/VLMEvalKit#101]
Thanks for the great effort of this repo! I see you provide the zero-shot results of several MLLMs on ScienceQA-IMG dataset. Could you please add the detailed results (i.e., NAT, SOC, LAN) of the TEST and VAL partitions?

**Comment by kennymckormick** [comment]
Hi, @thecharm, 
I will add these results later.

**Comment by zhangwengyu999** [comment]
Looking forward to the result as well 🥳

**Comment by kennymckormick** [comment]
Hi, @zhangwengyu999 , 
The detailed results are now available at https://openxlab.org.cn/apps/detail/kennyutc/open_mllm_leaderboard.
