### ISSUE TITLE
The md5 hashtest of the dataset DocVQA_VAL hasn't passed.

### ISSUE THREAD

**Issue by EmberYS** [open-compass/VLMEvalKit#103]
I checked the Completeness of DocVQA_VAL after downloading it from [here](https://opencompass.openxlab.space/utils/VLMEval/DocVQA_VAL.tsv).  Not sure which one is correct, please take a correct.

![image](https://github.com/open-compass/VLMEvalKit/assets/35883846/2d662c9c-17c6-4a53-a594-aed3d9d2c846)

**Comment by kennymckormick** [comment]
Hi, @EmberYS  ,
That's due to you are not using the latest code, please fetch the latest main branch and retry.

**Comment by EmberYS** [comment]
Hi, @kennymckormick 
Although [PR#104](https://github.com/open-compass/VLMEvalKit/pull/104) fixed md5 of DocVQA_VAL,  the column of “answers” in DocVQA_VAL doesn't fit code here. 
![image](https://github.com/open-compass/VLMEvalKit/assets/35883846/285d8d2f-dd77-4028-b61a-ff0eec97fb32)
This error leads to:
![image](https://github.com/open-compass/VLMEvalKit/assets/35883846/a8d8856b-d41a-4c8a-b256-52dba2930ece)
This seems to require modifying the code for DocVQA_VAL ( I tested repalcing "answer" with "answers".  Passed !) or dataset of DocVQA_VAL. Also pleased to open a pull request if helpful.

**Comment by llllIlllll** [comment]
HI, @EmberYS 
The bug in DocVQA has been resolved, please refer to #111   to modify the dataset_md5_dict and then reload DocVQA dataset.

**Comment by kennymckormick** [comment]
Hi, @EmberYS ,
As verified by myself, the problem of DocVQA has been fixed now. I tried to evaluate InternLM-XComposer2 on DocVQA_VAL, and obtained a 58.6 score.
