### ISSUE TITLE
(feature request) can we add load_dotenv() as a small quality of life improvement?

### ISSUE THREAD

**Issue by kdu4108** [open-compass/VLMEvalKit#107]
Hi OpenCompass VLMEvalKit team,

Thank you for your hard work on this project! I have a very minor feature request - can we add[ load_dotenv](https://pypi.org/project/python-dotenv/) to make it easier for users to run without explicitly setting their `OPENAI_API_KEY` env variables in the terminal before their run? 

This way, a user can add their key to the variable once in a .env file and it will automatically be loaded.
Happy to open a pull request if helpful.

**Comment by kennymckormick** [comment]
Hi, @kdu4108 ,
That's a good idea and we may add it on our TODO list. If you are also interested to do so, welcome to create a PR  for it.

**Comment by kennymckormick** [comment]
The feature has been implemented in #120 . See https://github.com/open-compass/VLMEvalKit/blob/main/Quickstart.md for  the detailed usage.
