### ISSUE TITLE
Evaluation of custom models and datasets.

### ISSUE THREAD

**Issue by juxingyiwan** [open-compass/VLMEvalKit#108]
VLMEVALKIT is a pretty convenient evaluation tool for MLLMs. I hope that the esteemed authors can create a framework for VLMEVALKIT that supports the evaluation of custom models and custom datasets. This framework can define a unified MLLM input-output interface and the conversion format for datasets.

**Comment by kennymckormick** [comment]
Hi, @juxingyiwan ,
we are going to first implement for custom multiple-choice datasets, and will create a tutorial for it. Stay Tuned!

**Comment by kennymckormick** [comment]
Hi, @juxingyiwan , custom multiple-choice dataset is supported now. Just prepare your dataset following the typical format of MCQ datasets in VLMEvalKit, place it under ~/LMUData, and use the tsv file name for running evaluation command.
