### ISSUE TITLE
MathVista测试问题

### ISSUE THREAD

**Issue by mactavish91** [open-compass/VLMEvalKit#112]
请问MathVista-mini的Prefetch rate和Acc有什么区别？我测试发现Prefetch rate为52.8，acc只有44.1

**Comment by YongLD** [comment]
你怎么计算mathvista-mini的prefetch rate跟acc的，我看他这里只能用gpt-4做判断

**Comment by mactavish91** [comment]
> 你怎么计算mathvista-mini的prefetch rate跟acc的，我看他这里只能用gpt-4做判断

用api key

**Comment by kennymckormick** [comment]
Prefetch 没有实际意义，仅为统计输出结果使用，请以 GPT 的评测结果为准。
我后续会改变默认行为至不开启 prefetch 功能。

**Comment by YongLD** [comment]
没有key只能用Exact Matching mode了，就是精度会差几个点，exact matching mode还是有用的
