### ISSUE TITLE
HallusionBench的最终结果如何计算

### ISSUE THREAD

**Issue by echo840** [open-compass/VLMEvalKit#113]
HallusionBench最后的结果包含aAcc，fAcc，qAcc，请问最后的准确率是如何计算的？是否是这三者的平均？   另外MME的评测只包含preception部分吗？排行榜上好像是既包含preception又包含cognition。

**Comment by kennymckormick** [comment]
Hi, @echo840 
The score we reported is the average of aAcc, fAcc, and qAcc.
The evaluation of MME also includes cognition (we name it reasoning for now).
