### ISSUE TITLE
The scores calculated by VLMEvalKit differ from the score calculated on the MMBench website

### ISSUE THREAD

**Issue by jdy18** [open-compass/VLMEvalKit#121]
[MMBench_DEV_EN_openai_result.xlsx](https://github.com/open-compass/VLMEvalKit/files/14662296/MMBench_DEV_EN_openai_result.xlsx)

When testing the results in this table：

The result on the MMbench website
<img width="548" alt="image" src="https://github.com/open-compass/VLMEvalKit/assets/52999149/aff68167-701d-43c7-9518-4a71c486ed69">

By VLMEvalKit：
"split","Overall","AR","CP","FP-C","FP-S","LR","RR",  
"dev","0.7328178694158075","0.7638190954773869","0.8277027027027027","0.6223776223776224","0.7610921501706485","0.4745762711864407","0.7652173913043478"

**Comment by kennymckormick** [comment]
Hi, @jdy18 , 
That looks weird, please share the original prediction with me, thus I can get more information.

**Comment by jdy18** [comment]
> Hi, @jdy18 , That looks weird, please share the original prediction with me, thus I can get more information.

Are you referring to the. pkl file generated by vlmevalkit?

**Comment by jdy18** [comment]
> Hi, @jdy18 , That looks weird, please share the original prediction with me, thus I can get more information.

I think I have found the reason. I uploaded the openai_result table to the mmbench website instead of the original file. Do you know what difference between these two files leads to the difference in evaluation results?

**Comment by kennymckormick** [comment]
Oh, you cannot upload the openai_result table for evaluation, it only includes 1-pass for each question, and the corresponding evaluation result is under the VanillaEval setting.
