### ISSUE TITLE
llava_v1.5_7b wrong results on Seedbench_IMG

### ISSUE THREAD

**Issue by BonitoW** [open-compass/VLMEvalKit#128]
Hi,

I have checked the saved result of llava7b on the seedbench_image benchmark and found that: for some problems, the llava7b can give the right prediction but in the evaluation framework it shows that it will return wrong answers.

For example, for index = 1198,4307
![output1198](https://github.com/open-compass/VLMEvalKit/assets/41474500/508a380e-2b98-4d2f-8889-293637c157c5)
Which object is likely found in the boy's hand? A: A book B: A soccer ball C: A calculator D: A pencil

![output4307](https://github.com/open-compass/VLMEvalKit/assets/41474500/8dc1f2f7-e230-47ed-a036-4ee51be16476)
Where is the priest located in the image? A: In front of the stained glass window B: To the right of the bride and groom C: To the left of the bride and groom D: Behind the bride and groom

Can you help explain this? Thanks for your help!

**Comment by kennymckormick** [comment]
Hi, @BonitoW , 
Honestly, I'm not sure about the reason. Do you mean you got the right prediction when directly infer llava_v1.5_7b with those two questions? If so, I'll give a try.

**Comment by kennymckormick** [comment]
Hi, @BonitoW ,
any updates?
