### ISSUE TITLE
How to calculate overall score for HallusionBench

### ISSUE THREAD

**Issue by WizardMx** [open-compass/VLMEvalKit#133]
It seems it can produce aACC, qACC and fACC for the bench, but your [leaderboard](https://rank.opencompass.org.cn/leaderboard-multimodal) shows of its overall score. Do I have to turn to its original paper to access overall score? 
Thx!

**Comment by kennymckormick** [comment]
Hi, @WizardMx ,
The original paper did not include an "Overall" metric, we define it because we want to use a single number to represent the overall performance on HallusionBench. 
We define Overall Score as the average of aACC, qACC, fACC.
