### ISSUE TITLE
OSError: Incorrect path_or_model_id: 'xtuner/llava-internlm2-20b/projector'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

### ISSUE THREAD

**Issue by starlitsky2010** [open-compass/VLMEvalKit#138]
torchrun --nproc-per-node=8 --nnodes=1 --node_rank=0 --master_addr 10.255.xxx.xxx --master_port 8109 run.py --data LLaVABench --model llava-internlm2-20b --verbose

But I met the following problem below:
Traceback (most recent call last):
  File "/train-xxx/code/xxx/src/test_scripts/test.py", line 6, in <module>
    projector = AutoModel.from_pretrained(projector_path,
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 484, in from_pretrained
    resolved_config_file = cached_file(
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 462, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: 'xtuner/llava-internlm2-20b/projector'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

I also used the following script to have a test but got the same error by my side.
```
import os.path as osp
import torch
from transformers import AutoModel

projector_path="xtuner/llava-internlm2-20b/projector"
projector = AutoModel.from_pretrained(projector_path,
                                              trust_remote_code=True,
                                              torch_dtype=torch.float16,
                                              device_map='cpu')
```

**Comment by kennymckormick** [comment]
Hi, @starlitsky2010 ，
Would you please paste the full error traceback here, seems I can not find codes related to VLMEvalKit here in your traceback.

**Comment by kennymckormick** [comment]
Feel free to re-open the issue for any further updates.
