### ISSUE TITLE
Can not reach the info_vqa dataset

### ISSUE THREAD

**Issue by Ezra-Yu** [open-compass/VLMEvalKit#146]
The link of [info_vqa](https://opencompass.openxlab.space/utils/VLMEval/InfoVQA_TEST.tsv ) is unreachable.

the same as `DocVQA_TEST` `InfoVQA_VAL` `InfoVQA_TEST`

**Comment by kennymckormick** [comment]
It should be OK now, you can have a retry.

**Comment by Ezra-Yu** [comment]
Thanks!
