### ISSUE TITLE
[Feature Request] RealWorldQA Benchmark

### ISSUE THREAD

**Issue by StarCycle** [open-compass/VLMEvalKit#149]
Would you like to add this benckmark ([introduction](https://x.ai/blog/grok-1.5v), [dataset](https://data.x.ai/realworldqa.zip)) to VLMEval? It's a multi-choice dataset and can be easily added to this repo.

Some examples:
<img width="433" alt="image" src="https://github.com/open-compass/VLMEvalKit/assets/33491471/0ef012c2-1102-4da4-8f33-aefe47658cbe">
<img width="446" alt="image" src="https://github.com/open-compass/VLMEvalKit/assets/33491471/4875d368-a908-46bd-a6da-76fd82101a27">
<img width="428" alt="image" src="https://github.com/open-compass/VLMEvalKit/assets/33491471/e6a8166e-49c5-4491-857e-7f8a51799b73">
<img width="425" alt="image" src="https://github.com/open-compass/VLMEvalKit/assets/33491471/eace298b-ae2a-4fab-b7ed-fa1772924ba7">

**Comment by kennymckormick** [comment]
@junming-yang

**Comment by StarCycle** [comment]
Thanks! I find it's just supported!
