### ISSUE TITLE
IndexError: index 1 is out of bounds for dimension 0 with size 1

### ISSUE THREAD

**Issue by lucasjinreal** [open-compass/VLMEvalKit#150]
cur_image_features = image_features[cur_image_idx]
                         ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
IndexError: index 1 is out of bounds for dimension 0 with size 1


Is there any reason why previous version can evaluate normally, but updated from git got such error? 

And this error happens only during evaluation at about 6%

Is there zero images samples in eval MMBench?

**Comment by lucasjinreal** [comment]
Am not sure as well, but just got this, I used llava model with qwen as LLM. The task is MMBenchCN

I used a try ... catch to generate_inner, not it can run, but looks like would effect the metric

**Comment by kennymckormick** [comment]
@lucasjinreal 
Please provide a command so that I can try to reproduce this problem.

**Comment by lucasjinreal** [comment]
Sorry, the exception got is on MMMU, not mmbench.

**Comment by icrto** [comment]
I am also experiencing the same problem when trying to run on MMMU. (I tried it with llava_v1.5_7b.)

**Comment by lucasjinreal** [comment]
@kennymckormick Can u take a look, actually didn't get this in previous version, some models actually didn't support more than 2 images in a single chat like llava.

**Comment by kennymckormick** [comment]
> @kennymckormick Can u take a look, actually didn't get this in previous version, some models actually didn't support more than 2 images in a single chat like llava.

OK, I will give a try for the llava_v1.5_7b x  MMMU configuration.
