### ISSUE TITLE
opencompass多模态榜单上的分数是exact_matching还是GPT辅助计算的分数

### ISSUE THREAD

**Issue by jiezhangGt** [open-compass/VLMEvalKit#154]
如题，请问opencompass多模态榜单上的分数是exact_matching还是GPT辅助计算的分数？如果没有openai Key的话，是不是得不到opencompass上榜单的分数？谢谢

**Comment by kennymckormick** [comment]
Hi, @jiezhangGt ,
1. 为 GPT 辅助计算的分数
2. 视模型而定，若模型指令遵循能力够强，则不需要 GPT 辅助

**Comment by jiezhangGt** [comment]
> Hi, @jiezhangGt ,
> 
> 1. 为 GPT 辅助计算的分数
> 2. 视模型而定，若模型指令遵循能力够强，则不需要 GPT 辅助

收到您的回复，谢谢~~
