### ISSUE TITLE
llava 34B 评测时CUDA out of memory

### ISSUE THREAD

**Issue by jiezhangGt** [open-compass/VLMEvalKit#156]
你好，我在评测llava 34B 时，有8张卡可用，发现只占了一张卡进行推理，导致CUDA out of memory。请问llava 34B的评测支持多卡评测吗？谢谢

**Comment by jiezhangGt** [comment]
已解决

**Comment by JesseZZZZZ** [comment]
请问您是怎么解决的呢？我遇到了相同的问题
