### ISSUE TITLE
There are some known issues with VQA tasks like OCRVQA, TextVQA, ChartQA, etc. We will fix them asap.

### ISSUE THREAD

**Issue by BlueBlueFF** [open-compass/VLMEvalKit#168]
请问这些问题修复了吗

**Comment by kennymckormick** [comment]
Hi, @BlueBlueFF , 
They are fixed now. But notice that we use zero-shot evaluation for all those benchmarks, which may show some difference compared to few-shot evaluation.

**Comment by BlueBlueFF** [comment]
> Hi, @BlueBlueFF , They are fixed now. But notice that we use zero-shot evaluation for all those benchmarks, which may show some difference compared to few-shot evaluation.

How to get DocVQA Score? should i use "anls"? but i got very low prefermence(5.3)
