### ISSUE TITLE
Support Blink Dataset

### ISSUE THREAD

**Issue by Ezra-Yu** [open-compass/VLMEvalKit#171]
一个更加关注 感知能力的数据集 Blink，非常纯粹的视觉感知benchmark。

https://zeyofu.github.io/blink/

<img width="457" alt="image" src="https://github.com/open-compass/VLMEvalKit/assets/18586273/2f9f21ec-808d-4d6c-aae5-ab018f2b27b5">

可以看出，GPT4V与人类水平有比较大的差距

**Comment by kennymckormick** [comment]
Hi, @Ezra-Yu , thanks for your suggestion and we will have a review on this dataset.

**Comment by junming-yang** [comment]
VLMEvalkit has supported BLINK.
