### ISSUE TITLE
支持LMDeploy作为推理后端

### ISSUE THREAD

**Issue by slchenchn** [open-compass/VLMEvalKit#179]
您好，目前VLMEvalKit支持LMDeploy server作为judge，是否有计划支持LMDeploy server作为需要被评测的模型

**Comment by kennymckormick** [comment]
Hi, @slchenchn , 
Currently we have no plan to support  lmdeploy served VLM. If you are interested, you can create a PR (including an API wrapper to call lmdeploy served VLM API), and we will help to review and merge.
