### ISSUE TITLE
怎么测试LLAVA+LLAMA3的性能？

### ISSUE THREAD

**Issue by xmu-xiaoma666** [open-compass/VLMEvalKit#181]
怎么测试LLAVA+LLAMA3的性能？

**Comment by kennymckormick** [comment]
@junming-yang

**Comment by junming-yang** [comment]
We have supported [Bunny-Llama3-8B](https://huggingface.co/BAAI/Bunny-Llama-3-8B-V),  a multimodal with language backbone Llama-3-8B. Please see for [#184](https://github.com/open-compass/VLMEvalKit/pull/184) more detail.

**Comment by junming-yang** [comment]
We have supported [LLAVA+LLAMA3](https://huggingface.co/xtuner/llava-llama-3-8b-v1_1). You can run `python3 run.py --model llava-llama-3-8b --data MMStar` to evaluate the model. And we will add the results into the [leaderboard](https://openxlab.org.cn/apps/detail/kennyutc/open_mllm_leaderboard) in the future.
