### ISSUE TITLE
About MMBench data source: Is there any difference from huggingface `lmms-lab/MMBench`?

### ISSUE THREAD

**Issue by Coobiw** [open-compass/VLMEvalKit#192]
Hello! I find it's accessible for me to use huggingface to get MMBench(`lmms-lab/MMBench`). For example:
```
from datasets import load_dataset
dataset = load_dataset(f"{my_path}/lmms-lab/MMBench/en")['validation'] # ['test']
```
Then, I get the EN val/test split data. Is there any difference between this repo/VLMEvalKit and `lmms-lab/MMBench`? Thanks for your reply!

**Comment by kennymckormick** [comment]
Hi, @Coobiw ,
I'm not sure, that data file is not served my VLMEvalKit thus I can not provide any guarantee.

**Comment by Coobiw** [comment]
thanks！i will double check it！
