### ISSUE TITLE
[Request]Consider integrating MMT-Bench and CONTEXTUAL?

### ISSUE THREAD

**Issue by iamlockelightning** [open-compass/VLMEvalKit#196]
MMT-Bench: A Comprehensive Multimodal Benchmark for Evaluating Large Vision-Language Models Towards Multitask AGI
https://arxiv.org/pdf/2404.16006

CONTEXTUAL: Evaluating Context-Sensitive Text-Rich Visual Reasoning in Large Multimodal Models
https://arxiv.org/pdf/2401.13311

**Comment by KainingYing** [comment]
Thanks for your interest in MMT-Bench. We will integrate MMT-Bench ASAP.

**Comment by kennymckormick** [comment]
Hi, @iamlockelightning 
MMT-Bench has already been supported.
