### ISSUE TITLE
mmmu should only use mmmu val not MMMU_DEV_VAL

### ISSUE THREAD

**Issue by max-yue** [open-compass/VLMEvalKit#198]

**Comment by kennymckormick** [comment]
Would you please further clarify the problem, It's OK to use Chinese.

**Comment by max-yue** [comment]
现在 mmmu 使用的是 dataset dev and validation split,  应该只使用val split

**Comment by kennymckormick** [comment]
Oh, we think it's OK to use MMMU_DEV_VAL, which only incurs an overhead of 150 visual questions. Besides, in the accuracy file we provide the scores for both MMMU_DEV and MMMU_VAL.
