### ISSUE TITLE
Model name in demo

### ISSUE THREAD

**Issue by chandrabhuma** [open-compass/VLMEvalKit#199]
I have used the demo given 
# Demo
from vlmeval.config import supported_VLM
model = supported_VLM['idefics_9b_instruct']()
# Forward Single Image
ret = model.generate(['assets/apple.jpg', 'What is in this image?'])
print(ret)  # The image features a red apple with a leaf on it.
# Forward Multiple Images
ret = model.generate(['assets/apple.jpg', 'assets/apple.jpg', 'How many apples are there in the provided images? '])
print(ret)  # There are two apples in the provided images.
It is working fine. But when I change the model other than idefics it is giving key error. Could u please clarify?

**Comment by kennymckormick** [comment]
Hi, @chandrabhuma,
would you please tell me which model are u using when encountered the error?

**Comment by chandrabhuma** [comment]
from vlmeval.config import supported_VLM
model = supported_VLM['deepseek-ai/deepseek-vl-7b-chat']()
--------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-3-97bd06052077>](https://localhost:8080/#) in <cell line: 3>()
      1 # Demo
      2 from vlmeval.config import supported_VLM
----> 3 model = supported_VLM['deepseek-ai/deepseek-vl-7b-chat']()
      4 # Forward Single Image
      5 ret = model.generate(['/content/fire.jpg', 'What is in this image?'])

KeyError: 'deepseek-ai/deepseek-vl-7b-chat'
For not only deepseek but also for other several models...Should I change the path  of the model?

**Comment by chandrabhuma** [comment]
Thank you  for the prompt response

**Comment by chandrabhuma** [comment]
I have uses the same line as given in demo
model = supported_VLM['deepseek-ai/deepseek-vl-7b-chat']()

**Comment by kennymckormick** [comment]
Hi, @chandrabhuma , 
That's not the correct usage. You should input the model_name that is defined in vlmeval/config.py

**Comment by chandrabhuma** [comment]
Now they are working..I am checking all the models. Thanks for the update and correcting me..
