### ISSUE TITLE
How to calculate avg score after the leaderboard update to 8 multimodal benchmarks

### ISSUE THREAD

**Issue by wanxinzzz** [open-compass/VLMEvalKit#206]
Take GPT4-o for example, AVG(82.8, 61.6, 62.8, 56.5, 51.7, 82.2, 663/10, 66.5) = 66.3

How can i get 63.9 as the leadborad show?

Thanks!

![leadboard](https://github.com/open-compass/VLMEvalKit/assets/32925088/e2bcabd7-734f-406d-97ea-74e5936a1e76)

**Comment by kennymckormick** [comment]
Hi, @wanxinzzz , 
The overall performance in this screenshot is wrong and has already been fixed now, please refresh the page to check the right results.
