### ISSUE TITLE
requirements.txt 不全

### ISSUE THREAD

**Issue by max-yue** [open-compass/VLMEvalKit#210]
比如没有 xformers 和 flash-attn
目前跑起来比较困难
也没有dockerfile

**Comment by kennymckormick** [comment]
Hi, @max-yue ,
1. 考虑到用户不一定会使用该代码库评测所有模型，因此，我们并未将所有模型的 requirements 都加入。一个我们采取的实践是：如果你可以正常运行该 VLM 的 DEMO，那么你应该能够在 VLMEvalKit 中正常使用这一模型
3. Dockerfile 问题：抱歉我们近期忙于一些其他任务，我们会在接下来一段时间 (希望在 6 月内) 完成 Dockerfile 的提供

**Comment by kennymckormick** [comment]
Duplicate of #190
