### ISSUE TITLE
有关模型和数据集下载的问题

### ISSUE THREAD

**Issue by xioatian1** [open-compass/VLMEvalKit#213]
非常感谢你们的工作！
我有个问题，是关于数据集和模型的，我是否能在运行执行评估任务命令之前就直接下载模型和数据集呢，由于我的服务器网络不能在评测的时候同步下载对应的数据集和模型，因此我想提前下载所需要的数据，并拷贝到项目里面，之后直接进行评估。请问这样是可行的吗？如果可行，希望您给我相关的建议或者操作方法。谢谢！

期待您的回复！

**Comment by kennymckormick** [comment]
所有数据集的下载地址在 VLMEvalKit/vlmeval/utils/dataset_config.py 的 dataset_URLs 中，可以采用 wget 命令下载；下载完成后同步到目标机器的 ~/LMUData 目录下就可以

**Comment by xioatian1** [comment]
感谢回复！
 我数据集已经下载到了VLMEvalKit项目的LMUData文件里面，模型也按照(例如：InternVL-Chat-V1-1)下载了
VLMEvalKit
--LMUData
--InternVL-Chat-V1-1
--......
这样是合理的吗？

**Comment by xioatian1** [comment]
> 所有数据集的下载地址在 VLMEvalKit/vlmeval/utils/dataset_config.py 的 dataset_URLs 中，可以采用 wget 命令下载；下载完成后同步到目标机器的 ~/LMUData 目录下就可以

感谢回复！
我数据集已经下载到了VLMEvalKit项目的LMUData文件里面，模型也按照(例如：InternVL-Chat-V1-1)下载了
VLMEvalKit
--LMUData
--InternVL-Chat-V1-1
--......
这样是合理的吗？

**Comment by xioatian1** [comment]
> 所有数据集的下载地址在 VLMEvalKit/vlmeval/utils/dataset_config.py 的 dataset_URLs 中，可以采用 wget 命令下载；下载完成后同步到目标机器的 ~/LMUData 目录下就可以

我按照我提到的目录去设置了数据集和模型，可是他还是会找不到数据集.tsv，请问是怎么回事呢？是不是评估要进行特定的网络检测呢
![image](https://github.com/open-compass/VLMEvalKit/assets/129817358/02cb9f41-0a82-4294-9d0f-2e8c6a48aa0b)

**Comment by junming-yang** [comment]
数据集 LMUData 应该放在 HOME 目录也就是 ~/LMUData 位置

**Comment by yfl-rgb** [comment]
请问一下~ 数据集的dataset_URLs是个tsv文件，怎么将数据集和对应的文本信息下载下来，另外最新版本 VLMEvalKit/vlmeval/utils/dataset_config.py已经不存在，怎么提前下载模型和数据集，再拿到脱网的环境下运行？

**Comment by YuanDaoze** [comment]
> 请问一下~ 数据集的dataset_URLs是个tsv文件，怎么将数据集和对应的文本信息下载下来，另外最新版本 VLMEvalKit/vlmeval/utils/dataset_config.py已经不存在，怎么提前下载模型和数据集，再拿到脱网的环境下运行？

I found the ULR in **VLMEvalKit/vlmeval/dataset/image_mcq.py**
