### ISSUE TITLE
AesBench support

### ISSUE THREAD

**Issue by yipoh** [open-compass/VLMEvalKit#222]
This is very meaningful work. Our AesBench (mostly MCQ) mainly evaluates the aesthetic perception ability of MLLM. If you want to add it to your framework, we can provide data support.  https://github.com/yipoh/AesBench

**Comment by kennymckormick** [comment]
Hi, @yipoh , 
I do appreciate the efforts you made on aesthetics evaluation of MLLMs. To add the benchmark to VLMEvalKit, please prepare a TSV file that is compatible with VLMEvalKit to me. For further details, you can reach me via email (dhd.efz@gmail.com) or wechat (dhd_efz).
