### ISSUE TITLE
Multi-GPU inference issue

### ISSUE THREAD

**Issue by ruifengma** [open-compass/VLMEvalKit#224]
When I try to run internVL-Chat-V1.5, since it is large and need at lease two GPUs, therefore, I use the following command to run
`CUDA_VISIBLE_DEVICES=2,3 python run.py --data MME --model InternVL-Chat-V1-5 --verbose`
But it does not run on the two GPUs but only one and give OOM error, do I need to give more configuration?

**Comment by kennymckormick** [comment]
Hi, @ruifengma ,
Sorry we have only supported evaluation on GPUs with 80G memories now (we will adapt to other low-profile GPUs very soon). A quick fix is to change L111 in `vlmeval/vlm/internvl_chat.py` from `.to(device)` to `.to('cuda')`

**Comment by ruifengma** [comment]
> L197 in `vlmeval/vlm/internvl_chat.py` the image data is loaded into a default GPU. Try to check the GPU id before loading the data.

Thanks @junming-yang , the image script I found is 
`pixel_values = load_image(image_path, max_num=self.max_num).cuda().to(torch.bfloat16)`
Do I need to dynamically check the id or force it to GPU 0 ? Since the model loading process is on 0 first then 1 (0 and 1 are projected by 2 and 3)

**Comment by junming-yang** [comment]
You can try to dynamically check the model's device.

**Comment by ruifengma** [comment]
> You can try to dynamically check the model's device.

I appended `.to(torch.cuda.current_device())` at the end, it still give me the same error

**Comment by junming-yang** [comment]
Maybe you can try `.to(self.model.device)`.

**Comment by ruifengma** [comment]
> Maybe you can try `.to(self.model.device)`.

Yes, I did. Still the same

**Comment by junming-yang** [comment]
I have tried to reproduce your bug. 
This is the revised code for running (from original code L107-110):
```
self.model = AutoModel.from_pretrained(model_path, torch_dtype=torch.bfloat16,
                                       trust_remote_code=True,
                                       load_in_8bit=load_in_8bit, device_map='auto').eval()
# if not load_in_8bit:
#     self.model = self.model.to(device)
```
Each GPU is allocated about 26 GiB. And no error is reported. Please check your code.

**Comment by ruifengma** [comment]
> I have tried to reproduce your bug. This is the revised code for running (from original code L107-110):
> 
> ```
> self.model = AutoModel.from_pretrained(model_path, torch_dtype=torch.bfloat16,
>                                        trust_remote_code=True,
>                                        load_in_8bit=load_in_8bit, device_map='auto').eval()
> # if not load_in_8bit:
> #     self.model = self.model.to(device)
> ```
> 
> Each GPU is allocated about 26 GiB. And no error is reported. Please check your code.

I actually did not DIY but completely following the advice. I use two A40 GPUs for the task, I checked and did the same modification as you did

**Comment by ruifengma** [comment]
Not coding issue, update the latest version of official internvl configurature file solve

**Comment by jinyu121** [comment]
I found that we should remove `self.model = self.model.cuda()` if we use `device='cuda', device_map='auto'`.
