### ISSUE TITLE
about vlmeval/evaluate/multiple_choice.py

### ISSUE THREAD

**Issue by mary-0830** [open-compass/VLMEvalKit#227]
请问作者，关于这个函数的用处是什么呢？在我评估MMStar时，这个build_choices好像没有起到任何的作用，并且好像还会导致匹配错误。

def build_choices(item):
    ret = {}
    for ch in string.ascii_uppercase:
        if ch in item and (not pd.isna(item[ch])):
            ret[ch] = item[ch]
    return ret

**Comment by junming-yang** [comment]
refer to issues #228
