### ISSUE TITLE
Image embeddings

### ISSUE THREAD

**Issue by chandrabhuma** [open-compass/VLMEvalKit#245]
Is it possible to obtain image embeddings from vision encoders of VLMs in this kit?

**Comment by junming-yang** [comment]
We are focused on VLM's prediction and result evaluation and currently do not support obtaining image embeddings.

**Comment by chandrabhuma** [comment]
Thank you for the prompt response

**Comment by chandrabhuma** [comment]
Thank you for the prompt response
