### ISSUE TITLE
如何多卡并行测评？How to evaluate on multiple cards in parallel?

### ISSUE THREAD

**Issue by buptweixin** [open-compass/VLMEvalKit#263]
## 问题描述

我需要测评一个 72B 的模型，这个模型放单张卡上会 OOM, 至少需要两块卡才能放下， 但是使用 `torchrun`  来运行时貌似只能放单张卡。

## 需要的帮助

如何使每个进程占用多张卡进行并行推理？

---

## Problem Description

I need to evaluate a 72B model, which will OOM if placed on a single card. It requires at least two cards to fit, but when using `torchrun` to run it, it seems that only one card can be used.

## Assistance Required

How can I make each process occupy multiple cards for parallel inference?

**Comment by junming-yang** [comment]
You can set `device_map='auto'` and use the command `CUDA_VISIBLE_DEVICES=0,1 python3 run.py --model xxx --data xxx`. Please refer to [Issues 224](https://github.com/open-compass/VLMEvalKit/issues/224).

**Comment by buptweixin** [comment]
> You can set `device_map='auto'` and use the command `CUDA_VISIBLE_DEVICES=0,1 python3 run.py --model xxx --data xxx`. Please refer to [Issues 224](https://github.com/open-compass/VLMEvalKit/issues/224).


It worked. Thank you very much.
