### ISSUE TITLE
如何获得 opencompass 上评测模型的最新细分项结果？

### ISSUE THREAD

**Issue by jyC23333** [open-compass/VLMEvalKit#264]
Hi，我看到 readme 中给了一个所有测试结果细分项的汇总 json -> http://opencompass.openxlab.space/utils/OpenVLM.json

但是这个不太全，请问下有全集吗

**Comment by junming-yang** [comment]
你好，我们评测过的结果都汇总到 [OpenVLM.json](http://opencompass.openxlab.space/utils/OpenVLM.json) 文件中了。

**Comment by jyC23333** [comment]
绝大多数模型的结果可以被找到，但目前 glm-4v-9b(开源模型) 没有在 json 中找到。
我能从哪里得到该模型的结果呢？
感谢

**Comment by junming-yang** [comment]
最新的模型结果迁移到 http://opencompass.openxlab.space/assets/OpenVLM.json 中了，我们将在 readme 中修正这个连接

**Comment by jyC23333** [comment]
非常感谢

**Comment by lily410** [comment]
@junming-yang 请问结果中是没有video benchmark(MMBench-Video Video-MME MVBench)的评测结果吗？

**Comment by FangXinyu-0913** [comment]
Hi @lily410， video benchmark的测试结果在 http://opencompass.openxlab.space/utils/video_leaderboard.json，也以leaderboard的形式展示在https://huggingface.co/spaces/opencompass/openvlm_video_leaderboard，欢迎关注！我们后续也会在readme里更新此链接

**Comment by FangXinyu-0913** [comment]
Hi @lily410，video benchmark的评测结果展示在 https://huggingface.co/spaces/opencompass/openvlm_video_leaderboard, 您也可以通过http://opencompass.openxlab.space/utils/video_leaderboard.json 这个链接进行下载，我们后续会在readme里加上此链接，感谢您的关注与支持！

**Comment by lily410** [comment]
> Hi @lily410，video benchmark的评测结果展示在 https://huggingface.co/spaces/opencompass/openvlm_video_leaderboard, 您也可以通过http://opencompass.openxlab.space/utils/video_leaderboard.json 这个链接进行下载，我们后续会在readme里加上此链接，感谢您的关注与支持！

看到了，十分感谢！
