### ISSUE TITLE
Does the generating params changed?

### ISSUE THREAD

**Issue by lucasjinreal** [open-compass/VLMEvalKit#269]
The model trends to output more words than a single option when multi choice, after upgraded vlmevalkit

**Comment by junming-yang** [comment]
@lucasjinreal Which model and dataset do you evaluate? Can you provide more information? This may help us find out the problem.

**Comment by kennymckormick** [comment]
Hi, @lucasjinreal , 
If you are testing in-house model , the problem may not be related to VLMEvalKit, you can check if the python environment accidentally changes (like you accidentally changed the version of some python packages).

**Comment by kennymckormick** [comment]
AFAIK, there is no change on the dataset side that would affect the model behavior.

**Comment by kennymckormick** [comment]
Close since no response in a long time, feel free to reopen if needed.
