### ISSUE TITLE
[BUG] local variable 'structs' referenced before assignment

### ISSUE THREAD

**Issue by Yunnglin** [open-compass/VLMEvalKit#271]
In file `vlmeval/inference.py`, line 41 , local variable `structs` referenced before assignment, see below:

<img width="1002" alt="image" src="https://github.com/open-compass/VLMEvalKit/assets/42505434/c2e9db8c-f13a-4bf3-bc6d-0ea54f1e4891">

**Comment by junming-yang** [comment]
Thank you for your report. We have fixed this problem in [pr275](https://github.com/open-compass/VLMEvalKit/pull/275). Now the API model can be used.
