### ISSUE TITLE
[bug] The same sample was run twice in mp_utils.py

### ISSUE THREAD

**Issue by buptweixin** [open-compass/VLMEvalKit#272]
As you can see  in https://github.com/open-compass/VLMEvalKit/blob/c91b8b26dbe45594019827f246748b344b214300/vlmeval/utils/mp_util.py#L147 
the same sample has been run over and over again, resulting in a doubling of the inference speed. Is this in line with expectations, and if so, what is the reason for this, and I look forward to receiving an answer, thank you.

<img width="655" alt="image" src="https://github.com/open-compass/VLMEvalKit/assets/8131131/62f36da1-02f5-42d0-be3d-50c0900ccd40">

**Comment by kennymckormick** [comment]
@buptweixin 
I think that's a typo and should be fixed, we haven't noticed that before since we always use nproc > 1 when calling `track_progress_rich`,  we will fix it immediately and thanks for the information.
