### ISSUE TITLE
Difference between MMBench_DEV and MMBench_Test

### ISSUE THREAD

**Issue by royzhang12** [open-compass/VLMEvalKit#274]
HI, @kennymckormick 

Thanks for open-sourcing such a wonderful job.  As I can not find the score of the  MMBench_DEV, would you mind to tell me   what's the difference between the  MMBench_DEV and MMBench_Test benchmark.

**Comment by junming-yang** [comment]
You can run with `--data MMBench_DEV_EN` or `--data MMBench_TEST_EN` to predict the MMBench result. MMBench_DEV benchmark can be evaluated on your own device. MMBench_TEST needs to be submitted to the official service. Link: https://mmbench.opencompass.org.cn/mmbench-submission.
