### ISSUE TITLE
Missing `dataset_config.py`

### ISSUE THREAD

**Issue by beichenzbc** [open-compass/VLMEvalKit#282]
According to Quickstart.md, the data root can be changed in `vlmeval/utils/dataset_config.py`. However, the `dataset_config.py` is missing and I found this file in the old version. So how to change the data root in the latest version, thanks.

**Comment by kennymckormick** [comment]
Hi, @beichenzbc , 
The dataset codes have been refactored and we will update the document correspondingly.
For now, if you want to change the data root, you can set the env variable `$LMUData`, or reset the `img_root` variable of the corresponding dataset class (only if you just want to modify the place you save the images, refer to `vlmeval/dataset/image_base.py`)

**Comment by beichenzbc** [comment]
Thanks for quick reply, could you please share an example of how to set env variable $LMUData if i want to test a model on MMMU dataset.
