### ISSUE TITLE
How to create OpenVLM.json 

### ISSUE THREAD

**Issue by amitbcp** [open-compass/VLMEvalKit#288]
Thanks for Opensourcing the framework.

I was able to replicate(infer and evaluate) some models. I also wanted to aggregate the benchmarking as done in JSON,

Is their any script or instruction you can share for the same ?

**Comment by junming-yang** [comment]
Thanks for watching! We will update a script later for the OpenVLM.json file. You can attach your test result file to the issues or send  to our email. We will check the result and merge into the leaderboard. Thanks for your contribution!

**Comment by amitbcp** [comment]
Thanks @junming-yang 
If you have a rough script  to share in the meantime, I can clean that and push in the repo for easy reproducing the leaderboard .
 Or should it be done manually for now ?

**Comment by junming-yang** [comment]
Here’s a draft script for OpenVLM.json. [scripts.zip](https://github.com/user-attachments/files/16260601/scripts.zip)
You only need to provide a JSON file containing the model result you want to add, following the example format below. You do not need to include results for all models in the JSON.
```
{
    "YourModelName": {
        "META": {
            "Method": [
                "YourModelName",
                "https://yourmodelwebsite.com"
            ],
            "Parameters": "YourModelParameters",
            "Language Model": "YourLanguageModel",
            "Vision Model": "YourVisionModel",
            "Org": "YourOrganization",
            "Time": "YourDate",
            "Verified": "Yes/No",
            "OpenSource": "Yes/No"
        },
        "SEEDBench_IMG": {
            // Add relevant details here
        }
        ......
    }
}
```
Note that the model should be supported by the VLMEvalKit toolkit. We will help check and merge it to the leaderboard.

Thanks for your contribution!

**Comment by kennymckormick** [comment]
Please feel free to reopen the issue if needed.

**Comment by amitbcp** [comment]
@junming-yang : Can we please put the notebook in the scripts folder with the other notebooks ?
It would help better re-use and keep it updated with the new datasets that is added to the VLMEvalLeaderboard
