### ISSUE TITLE
Request Support for VILA

### ISSUE THREAD

**Issue by amitbcp** [open-compass/VLMEvalKit#293]
Thanks for open-sourcing the framework 

One of the LMMs which has been doing great work and has been iterating their models is VILA : https://github.com/NVlabs/VILA

It would be great to add the support for the same

**Comment by amitbcp** [comment]
If its okay I can work on a the PR to integrate the same @junming-yang @kennymckormick ?

**Comment by junming-yang** [comment]
Hi, @amitbcp. Thanks for your work to support the VILA model. Please don't hesitate to contact us if you need any help.

**Comment by amitbcp** [comment]
Sure will try to wrap it within this week !!

**Comment by junming-yang** [comment]
Thanks for your contribution. VILA is supported now!
