### ISSUE TITLE
[Question] Dataset not officially supported ?

### ISSUE THREAD

**Issue by amitbcp** [open-compass/VLMEvalKit#299]
While trying the benchmark, for many datasets the logs have

` Dataset MMMU_VAL is not officially supported`

Dataset may vary. Does that mean the results and benchmarks can be different ? How do we fix this, any suggestions ?

**Comment by junming-yang** [comment]
Please run with the command MMMU_DEV_VAL. It includes the results of validation and test. We list the dataset name and corresponding conmand in the readme file.
