### ISSUE TITLE
How to change a dataset to TSV file

### ISSUE THREAD

**Issue by ttguoguo3** [open-compass/VLMEvalKit#302]
According to Development.md, I need vlmeval/utils/dataset_config.py to change  a dataset to TSV file. But I can't find it.

**Comment by junming-yang** [comment]
Hi, @ttguoguo3. We are updating the development doc. You can refer to this [PR 296](https://github.com/open-compass/VLMEvalKit/pull/296). We will update the main branch soon.

**Comment by junming-yang** [comment]
We have updated it. Please refer to [Development.md](https://github.com/open-compass/VLMEvalKit/blob/main/docs/en/Development.md).
