### ISSUE TITLE
Change to GPT judgement

### ISSUE THREAD

**Issue by beichenzbc** [open-compass/VLMEvalKit#305]
Hello, the default judging method for a multi-choice dataset is exact-matching method. Could you give me an example of how to use GPT API to judge a MC task, thanks.

**Comment by kennymckormick** [comment]
Hi, @beichenzbc , 
To judge MCQ datasets with the help of GPT API, you just need to set the `OPENAI_API_KEY` environment variable (directly or in `VLMEvalKit/.env`). You can refer to the document (https://github.com/open-compass/VLMEvalKit/blob/main/docs/en/Quickstart.md) for more details.

**Comment by beichenzbc** [comment]
Thanks for quick reply, but we have already set OPENAI_API_KEY for letting GPT4-o answering question, but the evaluating still using exact-matching mode, should we set another value for both generating answers and evaluating answers using GPT4-o?

**Comment by kennymckormick** [comment]
Which benchmark are you evaluating?

**Comment by beichenzbc** [comment]
MMMU

**Comment by junming-yang** [comment]
Hi, @beichenzbc. Have you set the `OPENAI_API_KEY_JUDGE` and `OPENAI_API_BASE_JUDGE` in the .env file?

**Comment by beichenzbc** [comment]
Thanks, but we have already set OPENAI_API_KEY and OPENAI_API_BASE and run the following command: python run.py --data MMMU_DEV_VAL --model GPT4o
However, the output result shows a lot of "Failed in Prefetch, no GPT-based answer matching under `exact_matching` policy", indicating that it still using exact matching mode.
Should I set another value, i.e. 'OPENAI_API_KEY_JUDGE', for using API judgment?

**Comment by junming-yang** [comment]
You can try to set the `OPENAI_API_KEY_JUDGE` and `OPENAI_API_BASE_JUDGE`. Are your code the latest from the main branch?

**Comment by beichenzbc** [comment]
OK, I will try. I download the code a week ago.

**Comment by beichenzbc** [comment]
It still doesn't work, there're still lots of "Failed in Prefetch, no GPT-based answer matching under `exact_matching` policy".

**Comment by junming-yang** [comment]
Please try to pull the latest code, delete the evaluation file with the `openai_result` suffix, and rerun the command.

**Comment by beichenzbc** [comment]
Thanks, maybe I have found the error. The same OpenAI API key and base can work properly in generating answers. But in evaluation, it will cause: "UserWarning: OPENAI API is not working properly, will use exact matching for evaluation". Do you have any idea about why it doesn't work properly, thanks.

**Comment by beichenzbc** [comment]
I've solved the problem. The command should be `python run.py --data MMMU_DEV_VAL --model GPT4o **--judge gpt-4o**` and I add gpt-4o in the 144th line in `vlmeval/dataset/image_mcq.py` 
Again thanks for your quick reply and helpful advice. Best wishes!

**Comment by junming-yang** [comment]
Currently, we support 'chatgpt-0125' or 'gpt-4-0125' as a judge model. We will support more API models as judge soon.

**Comment by beichenzbc** [comment]
So will there be any problem of using GPT-4o as judging model? The accuracy juding by 4o is 0.642, which is quite normal.

**Comment by junming-yang** [comment]
No problem. However, to ensure fairness on the leaderboard, we need to use the same judge model for all models. Currently, we are using chatgpt-0125 to report all results.

**Comment by beichenzbc** [comment]
Got it, thanks!
