### ISSUE TITLE
Request for GPT-4o Generated Results on MMBench

### ISSUE THREAD

**Issue by mactavish91** [open-compass/VLMEvalKit#307]
Hello,  could you share the raw output generated by GPT-4o for each question in the MMBench dataset?

**Comment by kennymckormick** [comment]
Here are the raw predictions of GPT-4o on MMBench. 

[GPT4o_HIGH_MMBench_CN_V11.xlsx](https://github.com/user-attachments/files/16356805/GPT4o_HIGH_MMBench_CN_V11.xlsx)
[GPT4o_HIGH_MMBench_V11.xlsx](https://github.com/user-attachments/files/16356806/GPT4o_HIGH_MMBench_V11.xlsx)
