### ISSUE TITLE
Suspected error?

### ISSUE THREAD

**Issue by Shijinghang** [open-compass/VLMEvalKit#308]
![image](https://github.com/user-attachments/assets/84957058-f961-4737-9341-16ab4035c120)
An error occurred while calculating the COCO Caption score, indicating the position in image_caption.py as shown in the figure. Is this a code error?

**Comment by junming-yang** [comment]
Hi, @Shijinghang. What error do you meet? I tried to reproduce it but failed (model: InternVL2-1B). Can you provide more information?

**Comment by kennymckormick** [comment]
Issue closes due to no response in a long time. Feel free to re-open it when needed.
