### ISSUE TITLE
用于编码和解码图像的vlmeval/smp.py文件不存在

### ISSUE THREAD

**Issue by ttguoguo3** [open-compass/VLMEvalKit#309]
在development.md文件中提及了需要vlmeval/smp.py文件进行图像的编码和解码，但在实际中无法找到

**Comment by kennymckormick** [comment]
Hi, @ttguoguo3 , 
我们此前进行了代码重构，目前，这两个函数位于 `vlmeval/smp/vlm.py`，我们会对文档进行更新

**Comment by kennymckormick** [comment]
已更新文档

**Comment by ttguoguo3** [comment]
感谢！
