### ISSUE TITLE
MuirBench Integration

### ISSUE THREAD

**Issue by amitbcp** [open-compass/VLMEvalKit#321]
Hey @kennymckormick @junming-yang 

I want to add MuirBench Dataset to the kit. It has mutliple images for a single query. Does VLM support any such dataset which I can refer and create a PR ?

**Comment by kennymckormick** [comment]
Hi, @amitbcp ，I think you can refer to BLINK benchmark to support MUIRBench

**Comment by kennymckormick** [comment]
Benchmark Merged.
