### ISSUE TITLE
Fail to Download MathVision_MINI.tsv

### ISSUE THREAD

**Issue by beichenzbc** [open-compass/VLMEvalKit#328]
Hello, I'm trying to evaluate on MathVision_MINI dataset. Howeverm this download link https://[opencompass.openxlab.space/utils/VLMEval/MathVision_MINI.tsv](https://opencompass.openxlab.space/utils/VLMEval/MathVision_MINI.tsv) seems to have stopped working. Could you please give a link to download MathVision_MINI , thanks?

**Comment by kennymckormick** [comment]
Hi, @beichenzbc , the link has been fixed now.

**Comment by beichenzbc** [comment]
Thanks!
