### ISSUE TITLE
Custom dataset is not considered MCQ by models

### ISSUE THREAD

**Issue by zodiacg** [open-compass/VLMEvalKit#336]
VLMEvalKit version: commit 8e0aace0504d952a25e310a1de66a32c2c1476f1

I added a custom MCQ format dataset to LMUData directory. It is successfully loaded and shows "UserWarning: Will assume unsupported dataset **** as a Custom MCQ dataset".
However the model is not correctly called to build a MCQ prompt. After checking it seems `DATASET_TYPE` function only returns correct evaluation types for supported datasets (i.e. listed in its `DATASET_URL`).

Since there IS `CustomMCQDataset` and `CustomVQADataset` type, is it possible to return the correct dataset type for prompt building?

Building a tsv file is very straight forward without the need of modifications to VLMEvalKit codes, so I hope it can be better supported.

**Comment by kennymckormick** [comment]
Hi, @zodiacg , 
That makes sense, we plan to treat all custom benchmarks as MCQ benchmarks and will modify the code accordingly.

**Comment by kennymckormick** [comment]
Feature Supported.
