### ISSUE TITLE
可以加入Mantis模型的评测吗 相关模型如下

### ISSUE THREAD

**Issue by BrenchCC** [open-compass/VLMEvalKit#342]
https://huggingface.co/TIGER-Lab/Mantis-8B-siglip-llama3

**Comment by PangziZhang523** [comment]
AssertionError: Invalid image processor type: Idefics2ImageProcessor 请问怎么解决？

**Comment by BrenchCC** [comment]
> Idefics2ImageProcessor

更新一下transformers版本吧
