### ISSUE TITLE
如何更改数据下载的缓存目录

### ISSUE THREAD

**Issue by BrenchCC** [open-compass/VLMEvalKit#351]

**Comment by junming-yang** [comment]
在 .env 设置 `LMUData=` 文件夹路径

**Comment by fmbao** [comment]
> 在 .env 设置 `LMUData=` 文件夹路径

.env在哪儿呀，没找到

**Comment by BrenchCC** [comment]
> > 在 .env 设置 `LMUData=` 文件夹路径
> 
> .env在哪儿呀，没找到

自己创建就行了～
