### ISSUE TITLE
InternVL2-76B/ VILA Series

### ISSUE THREAD

**Issue by amitbcp** [open-compass/VLMEvalKit#355]
Hey @kennymckormick @junming-yang 

Sharing offline eval results to help updated the HF leaderboard
[InternVL2-76B.zip](https://github.com/user-attachments/files/16482630/InternVL2-76B.zip)
[vila_3b.zip](https://github.com/user-attachments/files/16482631/vila_3b.zip)
[vila_8b.zip](https://github.com/user-attachments/files/16482632/vila_8b.zip)
[vila_13b.zip](https://github.com/user-attachments/files/16482633/vila_13b.zip)
[vila_40b.zip](https://github.com/user-attachments/files/16482634/vila_40b.zip)

**Comment by kennymckormick** [comment]
Thanks you so much. We are working on validating those results.

**Comment by kennymckormick** [comment]
Hi, @amitbcp ，
All provided results has been validated and merged into the OpenVLM leaderboard.
