### ISSUE TITLE
如何手动下载数据，并且在代码中配置好路径

### ISSUE THREAD

**Issue by hxhcreate** [open-compass/VLMEvalKit#371]
如何手动下载数据，并且在代码中配置好路径

**Comment by junming-yang** [comment]
手动下载：查看对应 vlmeval.dataset 中，对应 dataset 名的 `DATASET_URL` 链接，通过wget进行下载；
配置路径：在 .env 文件中设置 `LMUData=/path/to/your/dataset`。
