### ISSUE TITLE
Any pypi package for this toolkit?

### ISSUE THREAD

**Issue by zhimin-z** [open-compass/VLMEvalKit#375]

**Comment by FangXinyu-0913** [comment]
You can see pypi Package dependencies list in https://github.com/open-compass/VLMEvalKit/blob/main/requirements.txt

**Comment by zhimin-z** [comment]
> You can see pypi Package dependencies list in https://github.com/open-compass/VLMEvalKit/blob/main/requirements.txt

I mean, is this tool installable?

**Comment by FangXinyu-0913** [comment]
You can install it by this
```
git clone https://github.com/open-compass/VLMEvalKit.git
cd VLMEvalKit
pip install -e .
```
and use it by this
```
from vlmeval import *
model_name = 'llava_v1.5_13b'  # for example
model = supported_VLM[model_name]() if isinstance(model_name, str) else model_name
model.generate('hello') # only text
model.generate(['./assets/apple.jpg', 'Please describe this image.'])  # text + image
```
Furthermore, we more recommend using the VLMEvalKit repository for one-click evaluation of multimodal models and benchmarks.

**Comment by zhimin-z** [comment]
> You can install it by this
> 
> ```
> git clone https://github.com/open-compass/VLMEvalKit.git
> cd VLMEvalKit
> pip install -e .
> ```
> 
> and use it by this
> 
> ```
> from vlmeval import *
> model_name = 'llava_v1.5_13b'  # for example
> model = supported_VLM[model_name]() if isinstance(model_name, str) else model_name
> model.generate('hello') # only text
> model.generate(['./assets/apple.jpg', 'Please describe this image.'])  # text + image
> ```
> 
> Furthermore, we more recommend using the VLMEvalKit repository for one-click evaluation of multimodal models and benchmarks.

Ok, I initially thought it had a Python package in PYPI like https://pypi.org/project/opencompass.
