### ISSUE TITLE
Dataset url access denied

### ISSUE THREAD

**Issue by qibinc** [open-compass/VLMEvalKit#386]
Hi there, it looks like the dataset server is down. Can someone take a look? Thank you!

<img width="843" alt="image" src="https://github.com/user-attachments/assets/fbb0b31a-f18c-49d6-817b-da663a138a86">

**Comment by kennymckormick** [comment]
Sorry, we have located the problem and is now fixing it.

**Comment by kennymckormick** [comment]
The problem has been fixed now, please have a retry.

**Comment by qibinc** [comment]
Thank you @kennymckormick a lot for the prompt fix!
