### ISSUE TITLE
TypeError in parallel API calling

### ISSUE THREAD

**Issue by moiSusu** [open-compass/VLMEvalKit#39]
![企业微信截图_17042675828124](https://github.com/open-compass/VLMEvalKit/assets/118104525/9b6168ed-27fd-4978-a954-7ea2a6325854)

I met this error when I called openai API  parallelly (nproc=4). I am not sure if this an error from the side of VLMEvalKit developpers...Could someone give me some tips for fixing it?

**Comment by kennymckormick** [comment]
Hi, @moiSusu . This bug is fixed in #40 , feel free to reopen this issue if you still have troubles with the latest code.
