### ISSUE TITLE
配置数据集的vlmeval/utils/dataset_config.py文件不存在

### ISSUE THREAD

**Issue by scl-01** [open-compass/VLMEvalKit#402]
设置在 VLMEvalKit 中支持的数据集名称（在 vlmeval/utils/dataset_config.py 中定义），这个文件没有在对应路径找到

**Comment by FangXinyu-0913** [comment]
Hi @scl-01 
由于先前对代码进行重构，这一文件目前已经不存在
你可以在Readme中查看当前支持的数据集，并在 vlmeval/dataset 下搜索该数据集具体的名字

**Comment by scl-01** [comment]
@FangXinyu-0913 怎么搜索具体名字呢，是以数据集名字命名的py文件吗

**Comment by FangXinyu-0913** [comment]
我们现在把数据集分成了几个大类，放在几个不同的文件内（比如image_mcq代表多模态视觉领域下的多项选择题），你可以根据你想测评的数据集的类型进到对应文件内，查看里面类的DATASET_URL的key名字，即为具体名字

**Comment by scl-01** [comment]
OK，看到了，感谢
