### ISSUE TITLE
Cannot Reproduce Results of LLaVA-1.5 on MMBench_DEV_CN

### ISSUE THREAD

**Issue by ppalantir** [open-compass/VLMEvalKit#404]
Thank you for your awesome work!

I followed the README.md and used command `python run.py --data MMBench_DEV_CN --model llava_v1.5_13b --verbose`, and found  the overall accuracy is much lower than LLaVA-1.5's reported result (MMBench-cn 63.6)
<img width="307" alt="image" src="https://github.com/user-attachments/assets/5b227a41-c0da-41b7-afee-6c2693e962aa">

**Comment by FangXinyu-0913** [comment]
The overall accuracy reported in LLaVA-1.5 is based on the MMBench_CN dataset, aggregated from the TEST set and the  DEV set. In my already established environment, I tested the overall accuracy of MMBench_CN to match the official one and ested the accuracy of MMBench_DEV_CN as shown below. The fact that you measured low is probably related to the environment. The part of the environment I built is as follows, you can refer to the upgrade and re-test.

![image](https://github.com/user-attachments/assets/419bf3ec-a5f4-4f57-97c7-ee3a8e688da0)
![image](https://github.com/user-attachments/assets/6eee1b39-7e63-481b-a57e-e0e69c8faf72)

**Comment by PhoenixZ810** [comment]
Hi,

Please refer to [issue#439](https://github.com/open-compass/VLMEvalKit/issues/439#issuecomment-2328773836) to see if you are experiencing the same problem.

Best regards.

**Comment by kennymckormick** [comment]
Hi, @ppalantir , 
We reproduce the problem and also find that the previous results of llava_v1.5 on some Chinese benchmarks (MMBench-CN, CCBench, etc.) can not be reproduced now. We have asked the authors of LLaVA but still cannot figure out the reason, so we have updated the leaderboard to align with the current evaluation results for now.
