### ISSUE TITLE
There is no answer field in DocVQA_TEST

### ISSUE THREAD

**Issue by palewithout** [open-compass/VLMEvalKit#405]
There is no answer field in DocVQA_TEST. How can I get the answer field?

**Comment by FangXinyu-0913** [comment]
DocVQA is a challenge raised by researchers, and you can find the details at https://rrc.cvc.uab.es/?ch=17&com=introduction. The answer to DocVQA_TEST is not public because this challenge remains.
You can submit your results on this page to get your final results.
