### ISSUE TITLE
create new benchmark

### ISSUE THREAD

**Issue by yansuoyuli** [open-compass/VLMEvalKit#409]
您好，我想请问一下，如何把数据集变成这个框架下的.tsv文件呀？

**Comment by BrenchCC** [comment]
你这个问题问的不是很清楚，你可以根据数据集的类型例如MCQ，VQA，yes or no类型的问题去下载该框架下对应的tsv文件，在'''vlmeval/dataset’‘’路径下的脚本中记录着tsv的下载链接，参考相关的文件创建你自己的数据集的tsv文件以及相关处理接入代码
