### ISSUE TITLE
上传新的benchmark

### ISSUE THREAD

**Issue by ttguoguo3** [open-compass/VLMEvalKit#415]
我将新的benchmark：MM-NIAH的tsv格式数据存储到了https://huggingface.co/datasets/petter12321/MM-NIAH-VLMEvalKit/tree/main，其中MM_NIAH_VAL.tsv文件是完整的，而MM_NIAH_TEST.tsv文件被拆分成了part-aa~e五个文件，请将这五个文件组合成MM_NIAH_TEST.tsv文件而后将这两个tsv文件上传到服务器中，谢谢！

**Comment by kennymckormick** [comment]
Working.
