### ISSUE TITLE
The Dataset Names

### ISSUE THREAD

**Issue by lixu6-alt** [open-compass/VLMEvalKit#417]
Hi,

Does anybody know where to find the dataset names that can be passed to the run.py? In the README, I am told to find the names in defined in vlmeval/utils/dataset_config.py, however, I couldn't find this configuration file in the given directory.

Thanks.

**Comment by lixu6-alt** [comment]
I have found the names in a table at the upper part of the README file.

**Comment by FangXinyu-0913** [comment]
https://github.com/open-compass/VLMEvalKit/issues/402
