### ISSUE TITLE
修改结果路径

### ISSUE THREAD

**Issue by helloworld01001** [open-compass/VLMEvalKit#421]
你好！请问怎么修改结果路径，假如我的模型是llava-v1.5-7b，它会默认保存在/VLMEvalKit的目录下，llava-v1.5-7b的评测结果会保存在/VLMEvalKit/llava-v1.5-7b目录下，现在我想要这种效果/VLMEvalKit/my_test_result/llava-v1.5-7b，请问在哪里修改？

**Comment by wonderNefelibata** [comment]
请问如何实现的？

**Comment by wonderNefelibata** [comment]
> 请问如何实现的？

# Work Dir
    parser.add_argument('--work-dir', type=str, default='./outputs', help='select the output directory')

使用这个参数即可
