### ISSUE TITLE
cannot use Gemini

### ISSUE THREAD

**Issue by yansuoyuli** [open-compass/VLMEvalKit#435]
I cannot use Gemini

when use: GeminiProVision
2024-09-02 18:57:19,592 - ChatAPI - ERROR - 404 Gemini 1.0 Pro Vision has been deprecated on July 12, 2024. Consider switching to different model, for example gemini-1.5-flash.

when use: GeminiPro1-5 
    assert model == 'gemini-1.0-pro'
AssertionError

**Comment by PhoenixZ810** [comment]
Hi,

As indicated by the error message, the Gemini 1.0 Pro Vision model has been deprecated since July 12, 2024. Please switch to using the gemini-1.5-flash model.

Thank you!

**Comment by yansuoyuli** [comment]
Hi, how can I incorporate gemini-1.5-flash model in this framework?  Or can you please update the Gemini model? Thanks!

**Comment by PhoenixZ810** [comment]
Hi,

The latest version of vlmevalkit has has resolved this issue. Please refer to [gemini](https://github.com/open-compass/VLMEvalKit/blob/b779baa7681d73155489f3cb33c8c62a77be0842/vlmeval/api/gemini.py#L25) and use Gemini-1.5-pro. 


Thank you!

**Comment by PhoenixZ810** [comment]
> Hi, how can I incorporate gemini-1.5-flash model in this framework? Or can you please update the Gemini model? Thanks!

We will consider adding support for the gemini-1.5-flash model soon.
