### ISSUE TITLE
cannot use gpt-4v.

### ISSUE THREAD

**Issue by yansuoyuli** [open-compass/VLMEvalKit#436]
Log: {
    "error": {
        "message": "The model `gpt-4-1106-vision-preview` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}

**Comment by PhoenixZ810** [comment]
Hi,

As indicated by the error message, **the model gpt-4-1106-vision-preview has been deprecated**. Please switch to using other recent GPT models. All model names can be found in [api/gpt](https://github.com/open-compass/VLMEvalKit/blob/b779baa7681d73155489f3cb33c8c62a77be0842/vlmeval/api/gpt.py#L11).

Thank you!
