### ISSUE TITLE
About Tablevqabench score

### ISSUE THREAD

**Issue by mary-0830** [open-compass/VLMEvalKit#442]
Hello, may I ask which scores the TableVQAbench output should correspond to in the paper?
![image](https://github.com/user-attachments/assets/0333f34c-a42b-48e1-afd6-0af5bbef6789)

![image](https://github.com/user-attachments/assets/7bf071dd-bbdb-4245-a8ce-c7fbdbabc9e7)
And where should Input Modalities be set?

Thanks for your reply~

**Comment by FangXinyu-0913** [comment]
Hi @mary-0830, For TableVQABench, as of now VLMEvalKit only supports evaluating MLLMs, and the output modal only supports Vision, the specific four values that correspond to the four values of the same name on the table. The calculation of the average value is a bit off from my previous knowledge, maybe ask @hkunzhe.
