### ISSUE TITLE
MME-RealWorld Not Supported.

### ISSUE THREAD

**Issue by Haochen-Wang409** [open-compass/VLMEvalKit#449]
Hello, I found that MME-RealWorld has not been supported:
```bash
ERROR - Dataset MME-RealWorld is not valid, will be skipped.
```

**Comment by PhoenixZ810** [comment]
Hi,
this problem has been fixed just now.
Thank you!

**Comment by Haochen-Wang409** [comment]
Thanks for the prompt reply! The fix works for me.
