### ISSUE TITLE
测试程序经常中断

### ISSUE THREAD

**Issue by HZWHH** [open-compass/VLMEvalKit#453]
请问在跑测试程序时，为什么会经常中断？不改任何东西又可以继续跑，又会中断...

**Comment by Mor-Li** [comment]
您好，感谢你的反馈！能否提供更多相关信息，比如具体的运行命令、报错信息或中断时的日志？这样我们可以更好地帮助你解决问题。谢谢！

**Comment by HZWHH** [comment]
换了个环境，暂时没出现中断的问题，谢谢

**Comment by Mor-Li** [comment]
有任何问题可以随时重新打开或新建 issue。测试程序如果再次中断，欢迎提供更多信息，我们会尽量帮忙协助解决。
