### ISSUE TITLE
Input length of input_ids is 0, but max_length is set to -2009.

### ISSUE THREAD

**Issue by wangli68** [open-compass/VLMEvalKit#455]
When I run the latest  code with the following command
"python run.py --data MMBench_TEST_EN_V11 MMBench_TEST_CN_V11  --model InternVL2-76B --verbose"

Error：
ValueError: Input length of input_ids is 0, but max_length is set to -2009. This can lead to unexpected behavior. You should consider increasing max_length or, better yet, setting max_new_tokens.

python package:
transformers                   4.40.0
typing_extensions              4.9.0
torch                          2.2.1+cu121
torchaudio                     2.2.1+cu121
torchvision                    0.17.1+cu121

In this environment, I can run the original  InternVL2-76B without any errors.

**Comment by kennymckormick** [comment]
Hi,  @wangli68, 
I have fixed the `split_model` method for later torch versions (2.2+) in this commit: https://github.com/open-compass/VLMEvalKit/commit/7957e996434e2022cfa55772de31890310953934 (though I'm not sure if it is related to your question). 

Under a similar environment, the code run well on 4 A800 GPUs (when `load_in_8bit` is False, the evaluation of InternVL2-76B requires at least three 80G GPUs). The environment is:

```
transformers 4.40.0
typing_extensions 4.9.0
torch 2.2.2
torchaudio 2.2.2
torchvision 0.17.2
```

Evaluation screenshot (The `device logs are added for debugging): 

![image](https://github.com/user-attachments/assets/5e8f0f1a-f406-4b10-89c3-09af5ad1fa86)

GPU MEM Usage: 

![image](https://github.com/user-attachments/assets/76202dec-bf80-4421-925f-2cd5f9ac22c5)
