### ISSUE TITLE
InternVL2 Truncated Output

### ISSUE THREAD

**Issue by TJ-Ouyang** [open-compass/VLMEvalKit#466]
![image](https://github.com/user-attachments/assets/e38cad21-490a-434e-9c45-1b3a7764f34f)
When I use InternVL2-40B to do single image inference using personal data, the output is truncated.

**Comment by kennymckormick** [comment]
Hi, @TJ-Ouyang , 
That is strange, apparently the token number of the output is much smaller than the max_tokens set. Would you please share the content of your test.py so we may help with debugging?

**Comment by TJ-Ouyang** [comment]
> Hi, @TJ-Ouyang , That is strange, apparently the token number of the output is much smaller than the max_tokens set. Would you please share the content of your test.py so we may help with debugging?

We have solved the problem by setting "kwargs_default = dict(do_sample=False, max_new_tokens=512, top_p=None, num_beams=1)" before self.model.chat at line 359 in internvl_chat.py. We used ipdb and found the process did not go chat_inner function, where max_new_tokens was set before. 
![image](https://github.com/user-attachments/assets/2ef8e550-9b23-4311-988e-7adc5946edac)

**Comment by kennymckormick** [comment]
@TJ-Ouyang , 
I have figured out the cause of this problem: the default `max_new_tokens` for InternVL2-40B is just 20. I have changed the default kwargs value so that other users will not meet this problem again.

**Comment by kennymckormick** [comment]
https://github.com/open-compass/VLMEvalKit/blob/e542caea3cf5d362131bccdb97a70ce50839c332/vlmeval/vlm/internvl_chat.py#L177
