### ISSUE TITLE
'gpt-3.5-turbo-0613'已被废弃，建议将'gpt-3.5-turbo-0613' -> gpt-3.5-turbo

### ISSUE THREAD

**Issue by Cooperx521** [open-compass/VLMEvalKit#467]
![image](https://github.com/user-attachments/assets/899f6351-96e7-449c-a1cf-10e73fbf6402)
![image](https://github.com/user-attachments/assets/a7cf1b86-c906-4b4a-bc2b-ad9dbb52892d)
![image](https://github.com/user-attachments/assets/3ccf7f77-28e9-4a8a-bdeb-08143ca188a6)

**Comment by kennymckormick** [comment]
Hi, @Cooperx521 , 
我们最新的代码中应该已经移除了 gpt-3.5-0613 的使用， 请基于我们最新的代码进行评测。
