### ISSUE TITLE
infovqa_test测试时会报错

### ISSUE THREAD

**Issue by Cooperx521** [open-compass/VLMEvalKit#469]
![image](https://github.com/user-attachments/assets/80e2f259-207e-43d9-895e-e4ab1728c1cf)

**Comment by kennymckormick** [comment]
Hi, @Cooperx521 , 
InfoVQA_TEST does not include gt answer, so you can not obtain the metrics of InfoVQA_TEST w. VLMEvalKit.
You can evaluate the InfoVQA_val instead.
