### ISSUE TITLE
HallusionBench skips samples without images

### ISSUE THREAD

**Issue by ChuanyangZheng** [open-compass/VLMEvalKit#471]
Hello, 
     I follow your [Evaluation](https://github.com/open-compass/VLMEvalKit/blob/main/docs/en/get_started/Quickstart.md#step-2-evaluation) and evaluate HallusionBench using the script as follows:
`python run.py --data HallusionBench --model model --verbose --nproc=1`
The model generated 951 results, which skipped the samples without images. The HallusionBench benchmark should evaluate 1,129 samples, including some pure text samples. 

I found the possible cause lies in the [skip setting](https://github.com/open-compass/VLMEvalKit/blob/d1aafac1a7986881872ff8a80a8cc03cc6677691/vlmeval/dataset/image_base.py#L34). Running when setting skip_noimg=False will raise error. 

Do I miss something? Thanks for your time!

**Comment by kennymckormick** [comment]
Hi, @ChuanyangZheng , 
In VLMEvalKit we did not involve the pure-text samples, cuz they are not related to multi-modal evaluation.

**Comment by ChuanyangZheng** [comment]
Thanks for your reply, I also want to ask is the MMBench V1.1 in the [opencompass leaderboard](https://rank.opencompass.org.cn/leaderboard-multimodal/?m=REALTIME) evaluated in a way as follows?
`python run.py --data MMBench_V11 --model model --verbose --nproc=1`
But MMBench_V11 is a [Internal Only file](https://github.com/open-compass/VLMEvalKit/blob/1f96d21fbd81ce0d49c257e9cd343be89a5f23fb/vlmeval/dataset/image_mcq.py#L56).
We can only access MMBench_TEST_EN_V11 and MMBench_TEST_CN_V11. So can we use the following commands
```
python run.py --data MMBench_TEST_EN_V11 --model model --verbose --nproc=1
python run.py --data MMBench_TEST_CN_V11 --model model --verbose --nproc=1
```
and average these two results to get the result in the leaderboard?

**Comment by kennymckormick** [comment]
@ChuanyangZheng 

Yeah, and you need to submit the prediction file to https://mmbench.opencompass.org.cn/mmbench-submission to obtain the metrics.
