### ISSUE TITLE
如何测评大模型的效率

### ISSUE THREAD

**Issue by wenyu1009** [open-compass/VLMEvalKit#477]
测评使用起来非常方便，请问是否支持测评模型的效率？
如吞吐量这样的参数，后续是否会支持该功能。

**Comment by kennymckormick** [comment]
Hi, @wenyu1009 , 
一个模型的效率，会由多方面的因素决定：硬件、推理引擎、量化策略等。 对模型效率的评测超出了本 repo 的范畴。你可能可以在 vllm 或是 lmdeploy 中找到相应资源。

**Comment by wenyu1009** [comment]
好嘞，感谢回复
