### ISSUE TITLE
liuhaotian/llava-v1.6-vicuna-7b 评测时报错

### ISSUE THREAD

**Issue by Cooperx521** [open-compass/VLMEvalKit#480]
![image](https://github.com/user-attachments/assets/3f59a672-b776-4ac5-8b09-d1662d63d7c7)
已经将model_path更换为自己下载模型的位置，transformer也已经更新到最新版，这里的报错有点奇怪，因为官方仓库里面也没有这个文件
![image](https://github.com/user-attachments/assets/ebb341b7-0272-4adc-9d31-c6ddba3a2024)

**Comment by PhoenixZ810** [comment]
Please use this repo: https://huggingface.co/llava-hf/llama3-llava-next-8b-hf
