### ISSUE TITLE
how to run on multi-gpu with device_map='auto'

### ISSUE THREAD

**Issue by qianwangn** [open-compass/VLMEvalKit#482]
when I use 34B llm model, single-gpu will report OOM.
so I set device_map='auto', but It seems cant use torchrun, It takes too much time to inference.
how to solve this problem?

**Comment by kennymckormick** [comment]
Close the issue due to no response in weeks, plz reopen if needed

**Comment by qianwangn** [comment]
I use yi-34B LLM.
It seems visual encoder cost too much time.（32 frames per video）
