### ISSUE TITLE
MMBench_TEST 评估结果是否可以自动提交

### ISSUE THREAD

**Issue by Sync-yxh** [open-compass/VLMEvalKit#485]
评测 MMBench_TEST 后得到xlsx，需要手动提交到 MMB 的评估网站，是否可以在VLMEvalKit 中实现自动提交到评估服务器的功能？谢谢！

**Comment by FangXinyu-0913** [comment]
您好 @Sync-yxh, 目前我们尚不支持自动提交到评估服务器，需要您手动提交。该功能的开发目前暂时还未计划中。
