### ISSUE TITLE
Adding Pixtral from Mistral Team

### ISSUE THREAD

**Issue by amitbcp** [open-compass/VLMEvalKit#500]
Hey @kennymckormick @jinyu121 @FangXinyu-0913 :

I was planning to add : https://huggingface.co/mistralai/Pixtral-12B-2409 model to the eval framework.

The Mixtral team recommends using vllm for inference. Is it okay to introduce that dependency for the repo ?

If its okay I can go ahead and create a PR for the same

**Comment by kennymckormick** [comment]
Hi, @amitbcp , 
Since the repository supports hundreds of different MLLMs, we are not going to add the dependencies of a specific MLLM into the codebase dependency.

**Comment by amitbcp** [comment]
Sure @kennymckormick !

Will wait for Mixtral to integrate with transformers and then create a PR for the same
