### ISSUE TITLE
无法评测llava1.5-7b

### ISSUE THREAD

**Issue by itsqyh** [open-compass/VLMEvalKit#505]
transformers 版本是 4.37， 下载llava1.5-7b权重至本地后vlmeval/config.py 中llava-v1.5-7b的模型地址也做了修改，第一次run会正常下载数据集，但没有正常运行，也没有报错，直接结束了，请问有什么解决方法吗？
![image](https://github.com/user-attachments/assets/48369f79-de4c-4b09-b4eb-34e4d2378267)
![1844546e868c9c73ce1b5caa25167ee](https://github.com/user-attachments/assets/66b57c5d-4fe9-479f-b6c3-67ca8345fbc3)

**Comment by FangXinyu-0913** [comment]
您好！可能是您没有正确安装llava所引起下列报错导致退出，您可以安装后再次进行尝试。
![image](https://github.com/user-attachments/assets/9895521a-e523-4a3b-85d7-27520e3d60d4)

**Comment by yingyingxia666** [comment]
![微信图片_20241014101911](https://github.com/user-attachments/assets/4ca5f168-e154-4540-9450-be292cebf423)
我加载模型的时候很慢很慢 并且运行报错是为什么呀

**Comment by FangXinyu-0913** [comment]
这个提示是正常的，您加载完模型推理过程中，有出现其他报错吗
![image](https://github.com/user-attachments/assets/5f8536f1-8861-4776-ba89-8f77aad36fea)

**Comment by kennymckormick** [comment]
Feel free to re-open this issue for any further need.
