### ISSUE TITLE
XComposer cannot evaluate on Bench1_TEST

### ISSUE THREAD

**Issue by yansuoyuli** [open-compass/VLMEvalKit#507]
Hello my command is as follows:
python run.py --data Q-Bench1_TEST --model XComposer --verbose

But the result is comfusing:
<img width="794" alt="截屏2024-10-09 14 23 30" src="https://github.com/user-attachments/assets/a488acd6-494b-4622-8c5e-8e1964d1fa95">

**Comment by kennymckormick** [comment]
Hi, @yansuoyuli , 
Sorry for the confusion, Q-Bench1_TEST is a TEST split that does not include the ground-truth answer. I have updated the codes to add warning messages and information in the README.

BTW, here is the evaluation results of XComposer on Q-Bench1_VAL: 

![image](https://github.com/user-attachments/assets/b856004d-5a4d-4c34-95d0-368f3601e3a8)

**Comment by yansuoyuli** [comment]
How about Q-bench1_VAL？



---Original---
From: "Haodong ***@***.***&gt;
Date: Wed, Oct 9, 2024 16:27 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-compass/VLMEvalKit] XComposer cannot evaluate onBench1_TEST (Issue #507)




 
Hi, @yansuoyuli ,
 Sorry for the confusion, Q-Bench1_TEST is a TEST split that does not include the ground-truth answer. I have updated the codes to add warning messages and information in the README.
 
BTW, here is the evaluation results of XComposer on Q-Bench1_VAL:
 
image.png (view on web)

**Comment by kennymckormick** [comment]
> How about Q-bench1_VAL？
> […](#)
> ---Original--- From: "Haodong ***@***.***&gt; Date: Wed, Oct 9, 2024 16:27 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [open-compass/VLMEvalKit] XComposer cannot evaluate onBench1_TEST (Issue #507) Hi, @yansuoyuli , Sorry for the confusion, Q-Bench1_TEST is a TEST split that does not include the ground-truth answer. I have updated the codes to add warning messages and information in the README. BTW, here is the evaluation results of XComposer on Q-Bench1_VAL: image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

Q-Bench1_VAL is OK and I have pasted the results.

**Comment by yansuoyuli** [comment]
Hello, thanks for your answers. I want to further ask about the meaning of the metrics:
type_0_concern_0  type_0_concern_1  type_0_concern_2  type_0_concern_3  type_1_concern_0  type_1_concern_1  type_1_concern_2  type_1_concern_3  type_2_concern_0  type_2_concern_1  type_2_concern_2  type_2_concern_3
