### ISSUE TITLE
评测LLaVa系列模型时有bug

### ISSUE THREAD

**Issue by KingMV** [open-compass/VLMEvalKit#510]
您好！我在评测LLava系列模型时，会出现运行后，自动退出的情况，有时候不退出，有时候退出，不知道是什么原因

**Comment by FangXinyu-0913** [comment]
您好！可能是您没有正确安装llava触发了该错误所导致的退出，您可以在确认安装后再次进行尝试
![image](https://github.com/user-attachments/assets/c2951e13-8f56-4d40-b00b-8570a83eff26)

**Comment by KingMV** [comment]
> 您好！可能是您没有正确安装llava触发了该错误所导致的退出，您可以在确认安装后再次进行尝试 ![image](https://private-user-images.githubusercontent.com/81462011/375667588-c2951e13-8f56-4d40-b00b-8570a83eff26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MDA5NDQsIm5iZiI6MTcyODcwMDY0NCwicGF0aCI6Ii84MTQ2MjAxMS8zNzU2Njc1ODgtYzI5NTFlMTMtOGY1Ni00ZDQwLWIwMGItODU3MGE4M2VmZjI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDAyMzcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkYzAyZmMyZGE4Njc2MDViZTAxOTU0NWFhOWVmNzA4ZTBhYjcwMGYwYjczYWY0MGJiNTg3ZGY1OWJhMjZmMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._ny_CSPoMpVv2nM7JqH0uzQ7TyX0Xq6eIMGUjDHAckw)

您好！我check了代码，发现是load_pretrained_model函数会跳出
![image](https://github.com/user-attachments/assets/91c28921-665a-4aab-a40f-4b8435ff1fbc)

**Comment by FangXinyu-0913** [comment]
这个函数是llava内部自带的，您可以尝试在debug时把justMyCode设为false，进入函数内部查看具体报错

**Comment by KingMV** [comment]
找到错误了，因为网络问题，llava文件下的函数报错了，挂VPN就解决了。
