### ISSUE TITLE
About evaluating existing result file (xlsx for MMBench)

### ISSUE THREAD

**Issue by ligeng0197** [open-compass/VLMEvalKit#512]
Hello, I have locally generated the result file for **_LLaVA-1.5-13B_** on _MMBench-Dev-EN_ and obtained `llava-v1.5-13b.xlsx`. I would like to evaluate this result file directly. However, it seems that currently, only evaluation from scratch after generating the result file is supported as introduced in _Quick Start_. Could you please tell me if the current repository supports this feature?

**Comment by kennymckormick** [comment]
Hi,  @ligeng0197 , 
Would you please paste the file here so I can check what's wrong? 
Besides, the name of the result file should be llava-v1.5-13b_MMBench_DEV_EN.xlsx, if you didn't explicitly specify it.

**Comment by ligeng0197** [comment]
Thank you very much for your prompt response! I apologize if my explanation was unclear. The `llava-v1.5-13b.xlsx` file was generated using the original _LLaVA 1.5 code_. However, I would like to use VLMEvalKit locally to directly calculate the MMBench-dev metrics for the generated xlsx file, but I am not sure if this functionality feature is currently supported.

**Comment by ligeng0197** [comment]
> Hi, @ligeng0197 , Would you please paste the file here so I can check what's wrong? Besides, the name of the result file should be llava-v1.5-13b_MMBench_DEV_EN.xlsx, if you didn't explicitly specify it.

[llava-v1.5-13b.xlsx](https://github.com/user-attachments/files/17338203/llava-v1.5-13b.xlsx)
The generated file for reference.

**Comment by kennymckormick** [comment]
Hi, @ligeng0197 , 
You have to log in to use our evaluation service. 
The approach to evaluate MMBench DEV set w. VLMEvalKit has been sent to you via email.

**Comment by Batwho** [comment]
Hello,

I'm also wondering how to evaluate a existing xlsx file, as I would like to only evaluate on a subset of the generated xlsx file.
