### ISSUE TITLE
Integration of MuirBench

### ISSUE THREAD

**Issue by nicokossmann** [open-compass/VLMEvalKit#514]
Hi everyone, first of all the framework is great 😊

I had seen that you want to add [MuirBench](https://muirbench.github.io/) to the framework. The test data set was published on [Hugging Face](https://huggingface.co/datasets/MUIRBENCH/MUIRBENCH) with the corresponding answers. So I wanted to ask if an integration of the benchmark is planned?

**Comment by kennymckormick** [comment]
Hi, @nicokossmann , 
MUIRBench is already supported in VLMEvalKit (in PR #383 )
