### ISSUE TITLE
Support for Falcon2 VLM

### ISSUE THREAD

**Issue by Venkatesh-Balavadani** [open-compass/VLMEvalKit#515]
I would like to get the evaluation reproduced for Falcon2-VLM-11B model. Can you add the support for that model as part of the vlm class and config.py?

Thanks

**Comment by Venkatesh-Balavadani** [comment]
Resolved

**Comment by kennymckormick** [comment]
Hi, @Venkatesh-Balavadani , 
We have added it to our todo list and are working on it.

**Comment by kennymckormick** [comment]
Added in #556
