### ISSUE TITLE
Is A-OKVQA support discontinued?

### ISSUE THREAD

**Issue by MOSHIIUR** [open-compass/VLMEvalKit#518]
A while back A-OKVQA was supported, and I did try that out. Now, I am not seeing that in the ImageMCQDataset class. 
https://github.com/open-compass/VLMEvalKit/blob/058f6733a82954fd4c8c72dfc22c6b3881c93638/vlmeval/dataset/image_mcq.py#L43

**Comment by FangXinyu-0913** [comment]
Hi @MOSHIIUR. Sorry for accidentally deleting the link to the file due to our mistake, we've added it here (https://github.com/open-compass/VLMEvalKit/blob/main/vlmeval/dataset/image_mcq.py#L94), thank you very much for reminding us!
