### ISSUE TITLE
多次运行结果不一致

### ISSUE THREAD

**Issue by Wu-Zongyu** [open-compass/VLMEvalKit#521]
你好，请问还需要fix什么额外的seed吗？在运行很多开源模型比如llava-next-series和其他的系列模型的时候，多次inference发现有一些QA Pairs在不同inference轮次中输出不一致。

**Comment by kennymckormick** [comment]
Hi, @Wu-Zongyu , 
可以贴出不一致结果的示例吗？
我们在推理过程中，已有设定 temperature 为 0，但由于底层的随机性，仍可能在不同次的推理中有不同结果。但据观察，这点不太影响统计上的指标 (如数据集精度等)
