### ISSUE TITLE
评测InternVL2-8B出现OOM

### ISSUE THREAD

**Issue by AACengineer** [open-compass/VLMEvalKit#533]
python run.py --data MMMU_DEV_VAL --model InternVL2-8B --work-dir ./outputs  
使用8张显卡计算，每张显存是24GB

InternVL2-8B模型按照给定的split_model函数切分到8张卡上，跑MMMU_DEV_VAL数据集时会不定在某个case上报OOM错误，怀疑是显存被其他程序占用了导致网络中间的feature数据申请不到足够显存，如果是这样，VLMEvalKit有没有工具能够提前给feature预分配足够的显存避免OOM？

另：官方给出的多模态大模型评测结果，是在单卡显存80GB上跑出的吗？

![捕获](https://github.com/user-attachments/assets/034e548d-ded4-4f8c-a93f-90063b353894)

**Comment by kennymckormick** [comment]
Hi, @AACengineer , 
PR #566 has supported this feature, now you can set the environment variable `AUTO_SPLIT=1`, and use command
`python run.py --model InternVL2-8B --data MMMU_DEV_VAL` to use multiple GPUs for one VLM. We will soon update the related doc. 

AUTO_SPLIT: When set to 1 and launched N processes on a node w. M GPUs, each VLM will be distributed on M / N GPUs.

Here is a screen shot when I evaluate InternVL2-8B x MMMU_DEV_VAL on two 4090 GPUs, it works. 

![image](https://github.com/user-attachments/assets/25ecb190-ae71-4024-98ba-158504be66fc)

**Comment by kennymckormick** [comment]
@AACengineer Hi, has your question been solved?
