### ISSUE TITLE
AI2D数据集无法加载

### ISSUE THREAD

**Issue by zyy98123** [open-compass/VLMEvalKit#539]
我在使用SOLO-7B模型进行evolution时无法加载AI2D数据集
![微信图片_20241023000148](https://github.com/user-attachments/assets/0c0080f3-8c44-45ad-9dc7-4c0f7376e1fa)

**Comment by kennymckormick** [comment]
Hi, @zyy98123 , 
You should use AI2D_TEST or AI2D_TEST_NO_MASK (content in corresponding boxes not masked when choices are capital letters).
