### ISSUE TITLE
测试Video-MME_CN

### ISSUE THREAD

**Issue by jun0yayay** [open-compass/VLMEvalKit#543]
测试Video-MME_CN是否可行？
有建议怎么修改代码吗？比如是不是要把prompt改了

感谢！

**Comment by FangXinyu-0913** [comment]
Hi @jun0yayay, 想问一下您指的是哪个数据集呢，Video-MME好像暂未支持cn版本

**Comment by jun0yayay** [comment]
> Hi @jun0yayay, 想问一下您指的是哪个数据集呢，Video-MME好像暂未有cn版本

我方了没有是吗，那应该是我们自己弄的.............。

那是不是您觉得改改prompt应该就可以了？把原来英文的变成中文prompt

感谢！

**Comment by jun0wanan** [comment]
> Hi @jun0yayay, 想问一下您指的是哪个数据集呢，Video-MME好像暂未有cn版本

您好不知道您有建议的修改路线吗？

**Comment by kennymckormick** [comment]
Seems the benchmark is not an officially supported one. You can DM @FangXinyu-0913 for additional advice.
