### ISSUE TITLE
dataset_config.py在哪里

### ISSUE THREAD

**Issue by hello-bluedog** [open-compass/VLMEvalKit#545]
https://github.com/open-compass/VLMEvalKit/blob/main/docs/zh-CN/get_started/Quickstart.md#:~:text=%2D%2Ddata%20(list%5Bstr%5D)%3A%20%E8%AE%BE%E7%BD%AE%E5%9C%A8%20VLMEvalKit%20%E4%B8%AD%E6%94%AF%E6%8C%81%E7%9A%84%E6%95%B0%E6%8D%AE%E9%9B%86%E5%90%8D%E7%A7%B0%EF%BC%88%E5%9C%A8%20vlmeval/utils/dataset_config.py%20%E4%B8%AD%E5%AE%9A%E4%B9%89%EF%BC%89
vlmeval/utils文件夹下面没有dataset_config.py

**Comment by FangXinyu-0913** [comment]
https://github.com/open-compass/VLMEvalKit/issues/402

**Comment by kennymckormick** [comment]
The README has also been updated accordingly.
