### ISSUE TITLE
qwen2-vl-7b设置device_map为auto时报错

### ISSUE THREAD

**Issue by wwwbq** [open-compass/VLMEvalKit#546]
和之前的一些issue一样，使用V100 32G单卡推理时某些case会OOM，所以开了device_map希望把模型切分到多张卡上，但是用python和torchrun启动都会报错Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!，debug看了一下，具体问题出现在qwen2vl forward时，input_ids本来是在cuda:0上，但是embedding层被放在了cuda：1上，所以经过embeding后inputs_embeds的device就变成了cuda：1，而后续的一些其他变量仍然在cuda：0上。（transformers/models/qwen2_vl/modeling_qwen2_vl.py的1687-1695行）

想知道有没有什么简单的办法可以解决多卡推理一个模型的问题，实在是没有80g的卡

**Comment by kennymckormick** [comment]
对于其他模型，你可以照类似方式支持，或是提出需求

**Comment by kennymckormick** [comment]
Now there are some changes: 

Please set the environment variable `AUTO_SPLIT=1` if you want to distributed a model on multiple GPUs. Currently, the feature supported Qwen2-VL, Llava-OneVision, Llama-3.2, and InternVL2. 

If you need further VLMs to support this feature, you can comment here or create a PR follow #566

**Comment by PangziZhang523** [comment]
@wwwbq @kennymckormick "qwen2vl forward时，input_ids本来是在cuda:0上，但是embedding层被放在了cuda：1上，所以经过embeding后inputs_embeds的device就变成了cuda：1，而后续的一些其他变量仍然在cuda：0上" 这个问题现在多卡还是存在的，请问是怎么解决的？
