### ISSUE TITLE
gpt api_base不支持非develop模式

### ISSUE THREAD

**Issue by huakyouin** [open-compass/VLMEvalKit#547]
![image](https://github.com/user-attachments/assets/0b98f912-9c35-4659-a2bf-b9a42e082883)
gpt api如果没给deployment_name值会直接assert报错，但实际上有些api是非develop的，可参考azure内部实现
![image](https://github.com/user-attachments/assets/7f342b29-f029-488f-b2f9-799724c3b2ce)

**Comment by kennymckormick** [comment]
Hi，@huakyouin ，
这个是否方便提个 PR 修改一下？ Azure API 的 feature 本来是社区用户支持的，我们由于没有 Azure API  所以不好 DEBUG

**Comment by kennymckormick** [comment]
Feel free to re-open the issue for any further updates.

**Comment by ruiiu** [comment]
any update on how to use azure api, any steps to do that? Thanks very much
