### ISSUE TITLE
What is this code doing?

### ISSUE THREAD

**Issue by lerogo** [open-compass/VLMEvalKit#548]
What is this code doing?????

https://github.com/open-compass/VLMEvalKit/blame/490bb4e0fea0381eeeb43b75d289e7c6c2531e02/vlmeval/vlm/internvl_chat.py#L105

**Comment by kennymckormick** [comment]
Some times you need to run N procs on M GPUs (2 procs on 8 GPUs, etc.), 
the script will get the number of GPUs used by each proc under this circumstance.

**Comment by lerogo** [comment]
啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊！
