### ISSUE TITLE
MMBench这种选择题，是否可以考虑对prediction进行清洗。

### ISSUE THREAD

**Issue by xushilin1** [open-compass/VLMEvalKit#552]
<img width="561" alt="image" src="https://github.com/user-attachments/assets/0dc2e466-61a6-4591-8bca-b9309ac0d1ad">

模型已经预测了“选项B”，却算作错误。如果对prediction进行清洗，或者更改下评测代码，“选项B”也应该算作正确答案。

**Comment by SYuan03** [comment]
Hi, @xushilin1 您好
事实上我们已经进行了“清洗”，您看到的这条数据被认为hit=0应该是因为MMBench采用了CircularEval Strategy。
即每次都对选项和答案进行循环移位，以生成新的提示供VLM使用。只有当VLM在所有循环传递中正确预测答案时，它才被认为成功解决了该问题。具体您可查看[MMBench](https://arxiv.org/pdf/2307.06281)的Section 4.3内容。
