### ISSUE TITLE
Error when evaluating MMBench_TEST_EN

### ISSUE THREAD

**Issue by KosumosuL** [open-compass/VLMEvalKit#57]
Looks like the annotation in MMBench_TEST_EN does not contains the key "answer"? Yet the prefetch_acc has to access this key, as shown in https://github.com/open-compass/VLMEvalKit/blob/7f099c1f4b3bc99d9607651ce4f590bcf889e709/vlmeval/inference.py#L156

**Comment by YongLD** [comment]
Because The test_file have no key "`answer`", I think they forget to add the answer of the choise in the file `MMBENCH_TEST_EN`.

**Comment by kennymckormick** [comment]
Hi, @KosumosuL , 
The label of testing samples is confidential, to obtain the evaluation accuracy of MMBench test split, please upload it to the evaluation service of send it to opencompass@pjlab.org.cn

**Comment by KosumosuL** [comment]
> Hi, @KosumosuL , The label of testing samples is confidential, to obtain the evaluation accuracy of MMBench test split, please upload it to the evaluation service of send it to [opencompass@pjlab.org.cn](mailto:opencompass@pjlab.org.cn)

I can understand that. My point is, however, the code should consider this situation for avoiding this error, or the readme should point this out.

**Comment by kennymckormick** [comment]
> > Hi, @KosumosuL , The label of testing samples is confidential, to obtain the evaluation accuracy of MMBench test split, please upload it to the evaluation service of send it to [opencompass@pjlab.org.cn](mailto:opencompass@pjlab.org.cn)
> 
> I can understand that. My point is, however, the code should consider this situation for avoiding this error, or the readme should point this out.

Hi, @KosumosuL , that's a good point, I have fixed the problem in this commit: https://github.com/open-compass/VLMEvalKit/commit/e99204665a2cea7e6a006750c6526d820dacda7d, the evaluation skip for MMBench_TEST will be skipped on any non-official servers. You can try again on the latest main branch.
