### ISSUE TITLE
AMBER 对应的 DATASET_URL 失效

### ISSUE THREAD

**Issue by lihytotoro** [open-compass/VLMEvalKit#570]
[https://github.com/open-compass/VLMEvalKit/blob/main/vlmeval/dataset/image_yorn.py#L15](url)
您好，我发现这里 AMBER 对应的 URL 看起来已经失效了？

**Comment by kennymckormick** [comment]
Seems the implementation of AMBER has some bug, I'm checking with the PR author.

**Comment by kennymckormick** [comment]
Hi, @lihytotoro , 
The link has been fixed in this  commit: https://github.com/open-compass/VLMEvalKit/commit/c733356b0f36de5d53a7a17dee2b44fe0af2d225.

**Comment by kennymckormick** [comment]
> ###
> [Nov 4, 2024](#issuecomment-2454117169)

I found that the implementation of AMBER has some bug, the PR author is now trying to fix it @yfzhang114

**Comment by kennymckormick** [comment]
@ATing0203 @lihytotoro 

@yfzhang114 has already implemented the fix. Now the evaluation of AMBER should work well.

**Comment by kennymckormick** [comment]
Sample Results for GPT4o_MINI: 

---------  -------
Attribute  81.0304
Existence  87.2868
Relation   84.0745
Avg ACC    84.1306
---------  -------
