### ISSUE TITLE
upload failed on mmbench website

### ISSUE THREAD

**Issue by mactavish91** [open-compass/VLMEvalKit#59]
https://mmbench.opencompass.org.cn/mmbench-submission
![image](https://github.com/open-compass/VLMEvalKit/assets/58135925/b5e1c0d6-c1c7-442c-a1f8-3e12b590fbf2)

**Comment by kennymckormick** [comment]
Hi, @mactavish91 , our staff is trying to fix that problem. As a temporary solution, you can send your prediction files to opencompass@pjlab.org.cn and we will handle it manually.

**Comment by kennymckormick** [comment]
BTW, we have tried to submit a file and find it succeed. To find the reason of the error you encountered; please share the submission file with me.
