### ISSUE TITLE
llava-onevision multi-image

### ISSUE THREAD

**Issue by jun0wanan** [open-compass/VLMEvalKit#607]
llava-ov可以处理多图吗？不知道这个评测是否融入了多图还是只能单图或者视频？

**Comment by kennymckormick** [comment]
Hi, @jun0wanan , 

LLAVA-OV supports multi-image. Under VLMEvalKit, there exists benchmarks like BLINK that adopts multi-image setting.

**Comment by skimtea** [comment]
Hi, I encountered an issue while using the **BLINK benchmarks** to evaluate the llava_onevision_qwen2_7b_ov model. The error message displayed is shown below:
![image](https://github.com/user-attachments/assets/e7f2ed8e-2c0b-4520-b1c1-d06faadd34d9)
**Environment Details:**
**Transformers version:** 4.47.1
**Python version:** 3.10.12
**NVIDIA CUDA:** 12.1.105
I am using the official example code without any modifications. The issue has left me puzzled as everything seems set up correctly. Could you please help me resolve this bug as soon as possible?
Thank you in advance for your assistance!

**Comment by jun0wanan** [comment]
> Hi, I encountered an issue while using the **BLINK benchmarks** to evaluate the llava_onevision_qwen2_7b_ov model. The error message displayed is shown below: ![image](https://private-user-images.githubusercontent.com/49471673/398345348-e7f2ed8e-2c0b-4520-b1c1-d06faadd34d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyODI0ODksIm5iZiI6MTczNTI4MjE4OSwicGF0aCI6Ii80OTQ3MTY3My8zOTgzNDUzNDgtZTdmMmVkOGUtMmMwYi00NTIwLWIxYzEtZDA2ZmFhZGQzNGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDA2NDk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNTA4MWExZWFkYjNjOWM5OTdhYzgzOTA1ZTBiYTUyN2Y0OTE0ODIwYzBhMzdhYzJiODdiZWVmYjY4NjRjNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7deiapSqBCbS3MbksXrLVDlxmrQ4EPX2cIfdIrz9lNY) **Environment Details:** **Transformers version:** 4.47.1 **Python version:** 3.10.12 **NVIDIA CUDA:** 12.1.105 I am using the official example code without any modifications. The issue has left me puzzled as everything seems set up correctly. Could you please help me resolve this bug as soon as possible? Thank you in advance for your assistance!

您新开一个帖子问问吧？我的bench 不是这个
