### ISSUE TITLE
Get a 0 score  in Evaluation of qwen chat in ScienceQA

### ISSUE THREAD

**Issue by YongLD** [open-compass/VLMEvalKit#61]
As I said in the title, 

![image](https://github.com/open-compass/VLMEvalKit/assets/33275244/b1c18c22-6f07-466a-a557-b34ba9e184f9)

Why? I have some result in `qwen_chat_ScienceQA_TEST_prefetch.xlsx`:

![image](https://github.com/open-compass/VLMEvalKit/assets/33275244/8315cdb5-a639-407e-83fd-8eb73bf4f5d3)

But I have no answer with openai, should I must use openai api to evaluate the dataset?

**Comment by kennymckormick** [comment]
Hi, @YongLD , 
we are trying to reproduce this problem and will provide feedback asap.

**Comment by kennymckormick** [comment]
Hi, @YongLD , 
According to my experiment, this error will not occur on latest main branch. Would you please try again with our latest main branch? 
![image](https://github.com/open-compass/VLMEvalKit/assets/34324155/25b04165-f85a-45b6-8c71-636fd83e6162)

**Comment by YongLD** [comment]
Fantastic!! I didn't notice that you updated it two days ago. It works! Thanks for the amazing job.

**Comment by kennymckormick** [comment]
> Fantastic!! I didn't notice that you updated it two days ago. It works! Thanks for the amazing job.

😄 Please help star this project if you appreciate the efforts~
