### ISSUE TITLE
Where is the Mathverse result？

### ISSUE THREAD

**Issue by StarUniversus** [open-compass/VLMEvalKit#611]
https://mathverse-cuhk.github.io/#leaderboard is not the latest.
Also, https://huggingface.co/spaces/opencompass/open_vlm_leaderboard does not have this result.

**Comment by kennymckormick** [comment]
Hi, @StarUniversus 
Hi, we are working on delivering a new leaderboard on multimodal math reasoning, which will include the results on MathVerse. You can expect to see them in 2 / 3 weeks.

**Comment by kennymckormick** [comment]
Hi, @StarUniversus , 
You can now see the results of MathVerse in https://huggingface.co/spaces/opencompass/Open_LMM_Reasoning_Leaderboard
