### ISSUE TITLE
When running the Llama-3.2-90B-Vision model with an odd number of GPU cards, will encounter a device_map setting error

### ISSUE THREAD

**Issue by WeiweiZhang1** [open-compass/VLMEvalKit#626]

**Comment by WeiweiZhang1** [comment]
CUDA_VISIBLE_DEVICES=0,1,2

language_model.model.layers.99.input_layernorm.weight doesn't have any device set.

This error occurs due to the limited implementation of split_model() in vlmeval/vlm/llama_vision.py

**Comment by kennymckormick** [comment]
Hi, @WeiweiZhang1 , 
The problem has been fixed in a latest commit.
