### ISSUE TITLE
检查模型会遇到bug，如vlmutil check {MODEL_NAME}，如vlmutil check Llama-3.2-11B-Vision-Instruct

### ISSUE THREAD

**Issue by GoogleAlphaZero** [open-compass/VLMEvalKit#628]
vlmutil check {MODEL_NAME}，如vlmutil check Llama-3.2-11B-Vision-Instruct，会报错。注意，并非我模型路径错误导致。报错为importlib.metadata.PackageNotFoundError: No package metadata was found for vlmeval

**Comment by GoogleAlphaZero** [comment]
我拉取了最新的代码，运行vlmutil check Llama-3.2-11B-Vision-Instruct，报错变为了VLMEvalKit/vlmeval/dataset/__init__.py", line 168, in DATASET_TYPE
    if 'openended' in dataset.lower():
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by kennymckormick** [comment]
The problem has been fixed now.

**Comment by GoogleAlphaZero** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
