### ISSUE TITLE
执行MVBench评测时，发现两个问题，修改已放在评论中的附件里

### ISSUE THREAD

**Issue by Xiaoqi-Zhou916** [open-compass/VLMEvalKit#633]

**Comment by Xiaoqi-Zhou916** [comment]
1.由于MVBench部分数据视频被删除，导致评测时这部分的视频推理结果无法生成，评测结果无法正常读取，出现报错；2.在使用evaluate方法时，

**Comment by FangXinyu-0913** [comment]
Hi @Xiaoqi-Zhou916. 感谢您提出的问题及给出的解决方案，我们会在今日对这个问题进行修复～

**Comment by PangziZhang523** [comment]
修复了嘛 最新的代码还是有问题，报部分视频不存在的错误

**Comment by FangXinyu-0913** [comment]
![image](https://github.com/user-attachments/assets/c088b8dd-a55e-4c38-9dad-fca39f2ca6d6)
mvbench的部分视频可能需要您自己手动下载，或者您是在推理完成评估之后报的错吗，是否有详细的报错信息呢

**Comment by PangziZhang523** [comment]
如果要跳过这些没下载的数据，具体代码需要改动哪里

**Comment by FangXinyu-0913** [comment]
![image](https://github.com/user-attachments/assets/15817f1f-e7ef-4637-9ff9-d92361c8ffb7)
需要在这里把else后面的报错去掉，这样构建tsv的时候就会跳过那些数据，但这样会使得mvbench这个数据集缺少一部分数据，可能会影响对模型性能的评估
