### ISSUE TITLE
Invalid url of English and Chinese split of OlympiadBench

### ISSUE THREAD

**Issue by aiiph4** [open-compass/VLMEvalKit#634]
The links below are invalid: 
https://opencompass.openxlab.space/utils/VLMEval/OlympiadBench_EN.tsv https://opencompass.openxlab.space/utils/VLMEval/OlympiadBench_CN.tsv

**Comment by PhoenixZ810** [comment]
Hi there,

Thank you for reaching out and for your patience.

We've noticed that the link provided for OlympiadBench is indeed not working as expected. We appreciate your understanding, and our team is actively working on resolving this issue to restore access as soon as possible.

We sincerely appreciate your attention to detail and bringing this to our notice. Once the link is fixed, we will ensure to update this thread with the correct information.

**Comment by PhoenixZ810** [comment]
Hello,
We are sorry to inform that we will no longer provide separate support for OlympiadBench_EN and OlympiadBench_CN. Instead, VLMEvalKit now supports the unified [OlympiadBench](https://github.com/open-compass/VLMEvalKit/blob/2a66d654108837f5af4159e5543f27f407ac8de1/vlmeval/dataset/image_vqa.py#L435C9-L435C23) dataset.
We appreciate your understanding regarding this change. If you have any questions or need assistance with the transition, please do not hesitate to contact us.

Thank you for your understanding.

**Comment by aiiph4** [comment]
Thank you for your answer.
