### ISSUE TITLE
the infer speed is too slow

### ISSUE THREAD

**Issue by TuuSiwei** [open-compass/VLMEvalKit#635]
![image](https://github.com/user-attachments/assets/e82c9eff-1691-45ca-8441-17307a13e199)
I tested on textvqa based on the supported model, but why is the inference speed so slow as shown in the figure

**Comment by TuuSiwei** [comment]
I also tested several other data sets, and likewise infer was slow

**Comment by TuuSiwei** [comment]
@kennymckormick I'm sorry to bother you. Can you give me some advice

**Comment by kennymckormick** [comment]
Hi, @TuuSiwei ,
That's not normal, which model are you evaluating?
BTW, the reason might be that your output is too long (hundreds of tokens, etc.)

**Comment by TuuSiwei** [comment]
I appreciate your insightful advice. I found that "max_new_tokens" were initialized to 1024 in the model file. As follows
        kwargs_default = dict(temperature=float(0), num_beams=1, top_p=None, max_new_tokens=1024, use_cache=True)

Problem solved after I narrowed it down！
