### ISSUE TITLE
Can not download MM-Math and DynaMath dataset from the default links

### ISSUE THREAD

**Issue by HJYao00** [open-compass/VLMEvalKit#637]
DynaMath: https://opencompass.openxlab.space/utils/VLMEval/DynaMath.tsv
MM-Math: https://opencompass.openxlab.space/utils/VLMEval/MM-Math.tsv

Hello, the links are not working for downloading. Could you please update them?

**Comment by kennymckormick** [comment]
The links have been fixed now.
