### ISSUE TITLE
MMMU test set

### ISSUE THREAD

**Issue by mactavish91** [open-compass/VLMEvalKit#65]
It will be nice if VLMEvalKit can generate result for MMMU test set,

**Comment by kennymckormick** [comment]
Hi, @mactavish91 ,
The feature has been updated in https://github.com/open-compass/VLMEvalKit/pull/75.

**Comment by mactavish91** [comment]
@kennymckormick Thank you for you great effort! I wonder if there is a version that can be submitted to the MMMU leaderboard.
