### ISSUE TITLE
您好，能否增加一些中文的评估benchmark啊？比如CMMMU，支持的中文benchmark太少了

### ISSUE THREAD

**Issue by GoogleAlphaZero** [open-compass/VLMEvalKit#650]

**Comment by PhoenixZ810** [comment]
Hi,

Thank you for your interest and engagement with our project.

We are pleased to inform you that we now support the evaluation of Splitted Chinese benchmarks such as MMBench-CN. Should you wish to contribute by adding new Chinese benchmarks, we would be delighted to review your pull request.

**Comment by kennymckormick** [comment]
Hi, @GoogleAlphaZero , 
CMMMU has been incorporated in VLMEvalKit. 
If you have more suggestions, don't hesitate to comment here and we'll consider.
