### ISSUE TITLE
MathVerse_MINI 指向的 DATASET_URL 失效

### ISSUE THREAD

**Issue by lihytotoro** [open-compass/VLMEvalKit#652]
[https://github.com/open-compass/VLMEvalKit/blob/main/vlmeval/dataset/image_vqa.py#L269](url)
你好！这里 MathVerse_MINI 对应的 url 似乎失效了
![image](https://github.com/user-attachments/assets/4e8fdd95-67bc-46cc-9f4d-0b3e0460f326)

**Comment by lihytotoro** [comment]
另外，OlympiadBench_EN 和 OlympiadBench_CN 对应的 url 似乎也失效了？
[https://github.com/open-compass/VLMEvalKit/blob/main/vlmeval/dataset/image_vqa.py#L439](url)

**Comment by PhoenixZ810** [comment]
Hi,
we check the [MathVerse_MINI.tsv](http://opencompass.openxlab.space/utils/benchmarks/MathVerse/MathVerse_MINIV.tsv) and find it's still valid. We find the link of OlympiadBench is invalid, and we will fix it soon.
Thanks!
Hi there,

Thank you for reaching out and for your patience.

We have reviewed the [MathVerse_MINI.tsv](http://opencompass.openxlab.space/utils/benchmarks/MathVerse/MathVerse_MINIV.tsv) file, and we can confirm that it remains valid in our network. However, we've noticed that the link provided for OlympiadBench is indeed not working as expected. We appreciate your understanding, and our team is actively working on resolving this issue to restore access as soon as possible.

We sincerely appreciate your attention to detail and bringing this to our notice. Once the link is fixed, we will ensure to update this thread with the correct information.

**Comment by PhoenixZ810** [comment]
Hello,
We are sorry to inform that we will no longer provide separate support for OlympiadBench_EN and OlympiadBench_CN. Instead, VLMEvalKit now supports the unified [OlympiadBench](https://github.com/open-compass/VLMEvalKit/blob/2a66d654108837f5af4159e5543f27f407ac8de1/vlmeval/dataset/image_vqa.py#L435C9-L435C23) dataset.
We appreciate your understanding regarding this change.  If you have any questions or need assistance with the transition, please do not hesitate to contact us.

Thank you for your understanding.

**Comment by kennymckormick** [comment]
Hi, MathVerse_MINI 目前已可用，此外，VLMEvalKit 目前仅支持 OlympiadBench，不再支持 EN / CN 的 split
