### ISSUE TITLE
The locally saved glm-4v-9b model encounters errors during evaluation, which are related to the way the tokenizer is loaded

### ISSUE THREAD

**Issue by WeiweiZhang1** [open-compass/VLMEvalKit#653]
local model: https://huggingface.co/OPEA/glm-4v-9b-int4-sym-inc
![image](https://github.com/user-attachments/assets/f873c481-cb1f-4bb7-9695-6475a90ccb4b)

See issue in glm-v-9b for a similar error：
https://huggingface.co/THUDM/glm-4v-9b/discussions/35

**Comment by kennymckormick** [comment]
Hi, @WeiweiZhang1 , 
For custom models, you first need to add a wrapper and make sure the inference can be successfully performed. Then you can use VLMEvalKit for multi-modal evaluation.

**Comment by kennymckormick** [comment]
You can reopen the issue if there is any further problems
