### ISSUE TITLE
与榜单指标差距过大，MTVQA和MME

### ISSUE THREAD

**Issue by GoogleAlphaZero** [open-compass/VLMEvalKit#663]
用llama3.2-11b-vision
测试MTVQA的指标，您发布的为Overall:15.3，我实测为Overall:22.3812，
测试MME，您发布的指标为Perception:1380.9、Cognition:439.6，我实测为perception： 1319.5、Cognition:283
请问是什么原因？感谢，辛苦您解答或核实下榜单

**Comment by kennymckormick** [comment]
@FangXinyu-0913

**Comment by FangXinyu-0913** [comment]
您好，想问一下您是用我们的codebase进行评测吗，以及评测时的参数设定是怎么设定的呢，我们这边按您的设定再评测试一下

**Comment by GoogleAlphaZero** [comment]
没改参数，只是config内设置了llama3.2_11b_vision的路径，.env中设置了openai的密钥。运行命令为
python run.py --data MME MTVQA_TEST \
    --model Llama-3.2-11B-Vision-Instruct --nproc 4 \
    --work-dir /workspace/mydir \
    --verbose
    
  感谢！

**Comment by FangXinyu-0913** [comment]
我们这边重新测试了一遍，和榜单上的指标没有过大差别
![image](https://github.com/user-attachments/assets/0ef84811-0153-4335-9fe5-fa3b9c55b26c)
![image](https://github.com/user-attachments/assets/842a32be-d80e-4e65-8d43-bbd5c6b2c94b)
这是我们的环境
![image](https://github.com/user-attachments/assets/d033b8a9-7161-42ad-ab03-cac67bd84275)
想问一下您的环境配置是怎样的呢

**Comment by FangXinyu-0913** [comment]
Hi @GoogleAlphaZero, 由于您过久未回复这个问题，因此暂时关闭这个issue了。如果有问题的话欢迎您随时reopen或在此处回复联系我，感谢您的理解
