### ISSUE TITLE
OlympiadBench数量跟论文不一致

### ISSUE THREAD

**Issue by wdp-007** [open-compass/VLMEvalKit#667]
代码里的https://opencompass.openxlab.space/utils/VLMEval/OlympiadBench.tsv这个文件里question只有6765道题，但我看原论文里数学有6142，物理有2334，加起来有8476道题才对，请问这个数据是做了筛减吗？

**Comment by kennymckormick** [comment]
Hi, @wdp-007 , 
We don't keep those Theorem Proving questions in the original dataset since those questions need to be verified by human.
