### ISSUE TITLE
有InternVL 2.5和deepseek vl2的支持计划么

### ISSUE THREAD

**Issue by JohnTang93** [open-compass/VLMEvalKit#673]

**Comment by FangXinyu-0913** [comment]
internvl2.5目前已经支持了～另一个您指的是deepseek v2吗，目前还在规划当中

**Comment by ZihaoZheng98** [comment]
> internvl2.5目前已经支持了～另一个您指的是deepseek VL2吗，目前还在规划当中

 似乎仓库中没有 internvl2.5?

**Comment by FangXinyu-0913** [comment]
在config里是有的，可以调用，我们今天也补充一下readme～

**Comment by JohnTang93** [comment]
> 在config里是有的，可以调用，我们今天也补充一下readme～

我测了一下8B的，ChartQA指标是82.9，好像和paper里有差距

**Comment by kennymckormick** [comment]
Hi, @JohnTang93 , 
目前两类模型均已支持
