### ISSUE TITLE
关于 RealWorldQA 以及 MMMU_DEV_VAL 里面部分条目的问题

### ISSUE THREAD

**Issue by lihytotoro** [open-compass/VLMEvalKit#677]
你好！我在研究 RealWorldQA 的时候发现，某些题目在处理的时候似乎出现了选项的遗漏和错乱，并且和原始的正确答案对不上了。例如 index=105 的题目，在 huggingface 上找到原版题目：[https://huggingface.co/datasets/lmms-lab/RealWorldQA/viewer/default/test?p=1&row=105](url)
![image](https://github.com/user-attachments/assets/abc19543-c077-4c25-8e15-873ed83cd3c7)
与此同时，从 [https://github.com/open-compass/VLMEvalKit/blob/main/vlmeval/dataset/image_mcq.py#L87](url) 下载的 tsv 文件，关于这道题的选项则变成了两个，分别是原题的 A 和 C 选项：
![image](https://github.com/user-attachments/assets/decf1269-37ad-49c1-90ae-d2bd03a123e4)
类似这样的情况我猜是原始处理的时候由于原题 B 选项后面缺少 . 分隔符导致处理的时候忽略了？但是这题原始的正确答案是 C，如果按照 tsv 里的版本就不对了。

另外，关于 MMMU_DEV_VAL 也有部分题目可能存在问题，例如 validation_Geography_15
[https://huggingface.co/datasets/MMMU/MMMU/viewer/Geography/validation?row=14](url)
![image](https://github.com/user-attachments/assets/f58efe00-3c4a-4946-96a2-c2837175d7d5)
由于这题 D 选项是 None，因此在 tsv 中被记录成了和不存在选项相同的 NaN 值，这里由于时间关系暂时存疑的是，这是否会导致推理时只展示 ABC 三个选项？由于正确答案是 D，因此若只展示三个选项则本题无论如何回答不对了。
![image](https://github.com/user-attachments/assets/2ca4b040-f8cc-4526-9f05-157db442eeed)

**Comment by lihytotoro** [comment]
RealWorldQA 中 index=633 的行同样有类似的问题，C 选项被遗漏了：
![image](https://github.com/user-attachments/assets/1e8c4edf-1837-427b-b68a-d9033b472925)
![image](https://github.com/user-attachments/assets/45ab34d8-e088-4c20-af57-c9e354d55feb)

**Comment by lihytotoro** [comment]
另外，RealWorldQA 中 index=731 的条目，原始数据集忘记将 answer 处理成选项形式了，在 tsv 中也没有修正过来：
![image](https://github.com/user-attachments/assets/d09f7570-747b-44d5-95f8-3035a3fd0661)

**Comment by kennymckormick** [comment]
Hi, @lihytotoro 

好的，我们这边看一下

**Comment by kennymckormick** [comment]
Hi, @lihytotoro , 
All mentioned issues have been fixed in the new MMMU_DEV_VAL.tsv and RealWorldQA.tsv. We do not find anymore problems corresponding to the two benchmarks.
