### ISSUE TITLE
WildVision raises exception

### ISSUE THREAD

**Issue by YuanLiuuuuuu** [open-compass/VLMEvalKit#684]
During the evaluation of WildVision, the following exception was raised.

<img width="779" alt="截屏2024-12-23 14 49 46" src="https://github.com/user-attachments/assets/5838b295-c66c-47b8-af6b-218cea2de542" />

**Comment by PhoenixZ810** [comment]
Hi, 
Could you please show more details in the inference results of Wildvision?

**Comment by kennymckormick** [comment]
Hi, the problem has been fixed in #687
