### ISSUE TITLE
Llama-3.2-11B-Vision-Instruct来测评MMStar和HallusionBench

### ISSUE THREAD

**Issue by wangchunhui06** [open-compass/VLMEvalKit#685]
用Llama-3.2-11B-Vision-Instruct来测评MMStar和HallusionBench时，模型输出句子不完整（生成的prediction），大多数分词之后集中在130token。但是测MMVet时，就不会出现这种情况。

**Comment by FangXinyu-0913** [comment]
想问一下您使用的transformers版本是什么呢

**Comment by FangXinyu-0913** [comment]
您好，针对mcq和y/n数据集，我们将max_new_token设定成了128，您可以在https://github.com/open-compass/VLMEvalKit/blob/main/vlmeval/vlm/llama_vision.py#L200进行修改

**Comment by wangchunhui06** [comment]
知道啦，谢谢
