### ISSUE TITLE
ChartQA augmented & CMMMU

### ISSUE THREAD

**Issue by KosumosuL** [open-compass/VLMEvalKit#69]
It would be nice if VLMEvalKit can support evaluation on ChartQA augmented set and CMMMU, since it has supported ChartQA human set and MMMU

**Comment by kennymckormick** [comment]
Hi, @KosumosuL ,
ChartQA augmented is now incorporated. However, there is no news from the developers of CMMMU.

**Comment by junming-yang** [comment]
VLMEvalkit has supported ChartQA.
