### ISSUE TITLE
待测模型请求

### ISSUE THREAD

**Issue by MstarLioning** [open-compass/VLMEvalKit#690]
您好，请问必须选择supported给出的模型么？如果我对模型进行量化、剪枝后是否还能测试呢？谢谢！

**Comment by kennymckormick** [comment]
Hi，只需模型能够正常推理即可用 VLMEvalKit 测试，但如原 model wrapper 无法正常处理，需自行支持新的 model wrapper。

**Comment by MstarLioning** [comment]
收到，谢谢您的回复，我现在马上开始实验！
