### ISSUE TITLE
进行GQA评测时，相同index导致的结果覆盖问题

### ISSUE THREAD

**Issue by Lyxxx1211** [open-compass/VLMEvalKit#696]
![22](https://github.com/user-attachments/assets/8ab02f55-a44d-4d3e-a948-58d88c4df559)
进行GQA评测时，相同index导致的结果覆盖问题，由于index不唯一，导致同一个图片的多个问题index相同，最终评测结果中所有统一图片问的问题都是同一个答案，可以参考index：n329479的多个问题答案
[Uploading test.xlsx…]()

![WX20241225-212410@2x](https://github.com/user-attachments/assets/16941583-0879-4dd6-b764-4c3c5ff9f0d8)

**Comment by Lyxxx1211** [comment]
![33](https://github.com/user-attachments/assets/875488e9-4034-4434-a97d-df1d36dc874a)
再补充一张

**Comment by Lyxxx1211** [comment]
@FangXinyu-0913

**Comment by FangXinyu-0913** [comment]
HI，@Lyxxx1211 我们注意到了这个问题并确认存在，会在近期进行修复，感谢您指出这一问题

**Comment by FangXinyu-0913** [comment]
@Lyxxx1211 您好我们已经修复了这个问题，您可以在删除原先tsv后重新下载，即可获得正确结果。再次感谢您指出这一问题，如果有什么进一步的疑问，欢迎您随时在这一问题下提问或reopen这一问题。

**Comment by Purshow** [comment]
我在测试https://huggingface.co/HaochenWang/ross-qwen2-7b时候碰到了同样的问题
