### ISSUE TITLE
These two download links are no longer accessible...

### ISSUE THREAD

**Issue by zhimin-z** [open-compass/VLMEvalKit#78]
![image](https://github.com/open-compass/VLMEvalKit/assets/8592144/1a5b0ffa-550c-4dd4-b5b0-9ecbad569fc3)

**Comment by kennymckormick** [comment]
Hi, @zhimin-z , 
We have merged those numbers into a single json file ([OpenVLM.json](http://opencompass.openxlab.space/utils/OpenVLM.json)). Check our new README for more information.
