### ISSUE TITLE
LLava GPT Eval无法对齐

### ISSUE THREAD

**Issue by BlueBlueFF** [open-compass/VLMEvalKit#84]
在LLava中，Prompt是输出字母https://github.com/open-compass/VLMEvalKit/blob/main/vlmeval/vlm/llava.py#L96，然而在GPT Eval
中，https://github.com/open-compass/VLMEvalKit/blob/main/vlmeval/evaluate/multiple_choice.py#L75 却要求模型输出选项的内容，这里的Diff是为啥呢？

**Comment by kennymckormick** [comment]
@BlueBlueFF 
需要澄清的是，[multiple_choice.py#L75](https://github.com/open-compass/VLMEvalKit/blob/main/vlmeval/evaluate/multiple_choice.py#L75) 与推理多模态模型（如 LLaVA）无关，只是我们评测选择题时处理 **无法直接匹配选项字母** 情况的一种方式（即利用语言模型进行语义匹配）。
