### ISSUE TITLE
Unknown error when loading LLaVA model

### ISSUE THREAD

**Issue by cyj95** [open-compass/VLMEvalKit#92]
when I run the command
python run.py --data MMBench_DEV_EN MME SEEDBench_IMG --model llava_v1.5_13b --verbose
it shows
 warnings.warn('Unknown error when loading LLaVA model.')
<img width="659" alt="image" src="https://github.com/open-compass/VLMEvalKit/assets/31176427/ef253296-ab2f-477a-988a-f870e007ec0b">

how to deal with this?

**Comment by kennymckormick** [comment]
Hi, @cyj95 ,
Looks like this error is encountered when you failed to execute the following command:
![image](https://github.com/open-compass/VLMEvalKit/assets/34324155/dcef8522-67f4-4bf4-8ad8-5af0d5103e08)

Please clone the LLaVA repo: https://github.com/haotian-liu/LLaVA, install LLaVA from source (`pip install -e .`) and try again.

**Comment by EmberYS** [comment]
Hi, @kennymckormick 
I debug the run.py with args: "--data MME --model llava_v1.5_7b --verbose". The code always comes to here:
![image](https://github.com/open-compass/VLMEvalKit/assets/35883846/84a5c9ad-19a2-43a2-b86d-f5a8fb61c0b2)

The specific error shows:
![image](https://github.com/open-compass/VLMEvalKit/assets/35883846/cafce057-29a2-426c-902b-05ff814e649f)
Does it mean that environments without internet connectivity cannot works?

Installed verson of llava and vlmeval:
![image](https://github.com/open-compass/VLMEvalKit/assets/35883846/9bce2abf-7e50-489c-b23d-7d5c9190b73e)

Path of the dataset and model：
![image](https://github.com/open-compass/VLMEvalKit/assets/35883846/3a4c87ca-0a49-4b33-8ef5-390fb9542dd9)

any suggestions to resolve this issue, thanks!!!

**Comment by kennymckormick** [comment]
Hi, @EmberYS, 
Looks like a question about internet connectivity: you are trying to fetch openai clip from huggingface but failed.
